### ISSUE TITLE
TypeScript server now in testing

### ISSUE THREAD

**Issue by MrBrax** [MrBrax/TwitchAutomator#100]
https://github.com/MrBrax/TwitchAutomator/tree/develop-ts

Still pretty unstable, not all endpoints done yet. Major file structure changes, but easier to work with.

**Comment by KurtzPT** [comment]
I'll try to test it out sometime in the next week

**Comment by KurtzPT** [comment]
Trying out now (docker) and I can't change settings because the binaries configs are all required now (I never had to put anything there before)
