### ISSUE TITLE
Error saving settings with unexpected response

### ISSUE THREAD

**Issue by AdamSaketume26** [MrBrax/TwitchAutomator#114]
When I save settings this shows saying External app url responded with an unexpected response: 
![image](https://user-images.githubusercontent.com/72011070/164398612-5a4be7b8-8b96-4462-b065-d33bccc2bf28.png)

I look at network log and the PUT request resulted in 400 and responded with `{"status":"ERROR","message":"External app url responded with an unexpected response: "}`

This happened when I built manually on latest a516e56 and when I use Docker.

**Comment by MrBrax** [comment]
your app url needs to be a public facing url pointing to the site for the webhooks to post to, required for recording to work

**Comment by AdamSaketume26** [comment]
> your app url needs to be a public facing url pointing to the site for the webhooks to post to, required for recording to work

can i not run it locally on my network instead? I dont need webhooks either but if you say it is required then is a discord webhook fine?

**Comment by MrBrax** [comment]
if you want it to record channels when they go online you need a public facing address with https. not sure if i've set the settings to be optional

**Comment by AdamSaketume26** [comment]
that sucks i didnt expect to face any issues running it local wasnt expecting to require a specific server with a public domain to run the app. Your app looks useful but maybe ill use it in the future when there is local support

**Comment by MrBrax** [comment]
if you want to have it local only it would have to constantly check if a streamer is online every like 30 seconds, do that thousands of times a day and it would probably spam a bit too much. there are other projects like that, but i wanted it to be the least intrusive as possible

**Comment by AdamSaketume26** [comment]
> it would have to constantly check if a streamer is online every like 30 seconds, do that thousands of times a day

is your project not using eventsub to listen for when a streamer goes live?

**Comment by MrBrax** [comment]
> > it would have to constantly check if a streamer is online every like 30 seconds, do that thousands of times a day
> 
> is your project not using eventsub to listen for when a streamer goes live?

it does, and that's why it needs an url where twitch can send the data to

**Comment by AdamSaketume26** [comment]
i didnt know sorry. thank you for your help
