### ISSUE TITLE
Error: Axios is not initialized

### ISSUE THREAD

**Issue by AdamSaketume26** [MrBrax/TwitchAutomator#115]
I can't add any channels for some reason. I got error 400 again on the post.

![image](https://user-images.githubusercontent.com/72011070/164400359-714f466f-5b38-49d6-85e1-abd72c308f12.png)

```
| channel <DEBUG> Fetching channel data for login sodapoppin, force: true

| helper <DEBUG> Fetched access token from cache

 | route.channels.add <ERROR> Failed to create channel: Error: Axios is not initialized

"POST /api/v0/channels HTTP/1.1" 400 55 "http://192.168.1.142:8082/settings/newchannel" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
```

This happened when I built manually on latest a516e56 and when I use Docker.

**Comment by MrBrax** [comment]
axios not being initialised is a sign of the twitch client id/secret not being set, and if my code for re-configuring axios after saving doesn't work, an app restart is required

**Comment by AdamSaketume26** [comment]
> axios not being initialised is a sign of the twitch client id/secret not being se

i try to set it but I get the same problem in https://github.com/MrBrax/TwitchAutomator/issues/114 where it doesnt save. I restarted the container and saw that it didnt save. the keys stick on refresh but it did not really save.

**Comment by MrBrax** [comment]
the internal port is 8080 yes, the external port is what you set in the compose file or the run command. are there any errors about saving the config file?

**Comment by AdamSaketume26** [comment]
No errors except for what i mentioned in #114 but you say i need a public url for the app so i guess that is the issue

**Comment by MrBrax** [comment]
yeah it does set the config in memory but doesn't save them to disk when that check fails, something i have to look over.

reverse proxies between different hosts work if you can't have a direct link to the net from the server

**Comment by MrBrax** [comment]
https://twitter.com/TwitchDev/status/1469029140854677509?s=20

i guess it could be possible if and when this exists. i made the config thing optional in the develop-ts branch, but no recordings can be made still
