### ISSUE TITLE
TwitchDownloaderCLI permissions

### ISSUE THREAD

**Issue by StephanBruh** [MrBrax/TwitchAutomator#12]
Installed TwitchDownloaderCLI chmod +x it, entered the path but get a `sh: 1: exec: /usr/bin/TwitchDownloaderCLI: Permission denied` What permission does it need extra?

**Comment by MrBrax** [comment]
not actually sure as it's not my software, is it the right linux binary? is it maybe trying to write to a folder it doesn't have access to?

**Comment by StephanBruh** [comment]
Also tried doing it in other folders and in the main (/var/www/TwitchAutomator) folder but always the same error

**Comment by MrBrax** [comment]
maybe there are some security features in your distro i don't know about, not sure if i would be able to figure it out

**Comment by StephanBruh** [comment]
Fixed, changed folder owner
