### ISSUE TITLE
External App URL cannot contian port

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/TwitchAutomator#120]
Setup is behind reverse proxy and is build like so https://subdomain.domain.de
So there is no port anymwhere but get this error when trying to save settings suddenly.
Trust Proxy is enabled
![image](https://user-images.githubusercontent.com/8904984/164678558-bfa6ea78-7f08-4763-a9a9-7f6541ef34eb.png)

**Comment by MrBrax** [comment]
oh yeah of course, http:// includes a :

**Comment by MrBrax** [comment]
i've started putting in tests now, maybe that'll help 🤡

**Comment by Serph91P** [comment]
Nice one.
Btw is on the unRAID Community Applications:

https://forums.unraid.net/uploads/monthly_2022_04/image.png.88183f130a3832e23b8cbd3bb4691cf8.png
