### ISSUE TITLE
External URL is invalid: External app url responded with an unexpected response:

### ISSUE THREAD

**Issue by stayupthetree** [MrBrax/TwitchAutomator#124]
I have a subdomain setup on a reverse proxy, https://twitch.notsharing.net
Logs don't give anything of any relevance to help narrow it down

**Comment by MrBrax** [comment]
if you visit the url https://subdomain.example.com/api/v0/hook , what is the response? it should return something, otherwise your reverse proxy isn't set up correctly. i don't think i've broken anything recently

**Comment by stayupthetree** [comment]
It returns "No data supplied"

**Comment by MrBrax** [comment]
then it should work. is the server behind a firewall without loopback nat? can the server curl the external url?

**Comment by stayupthetree** [comment]
Hmm interesting it is working now, Im thinking a DNS issue actually. Having another issue, but I'll open a ticket if I can't figure it out.

**Comment by MrBrax** [comment]
it's always dns :^)
