### ISSUE TITLE
Webhook running since 2h but stream online since seconds.

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/TwitchAutomator#136]
Sorry for opening so many Issues, my offer still stands ;)

Now to the bug:
tested with my own stream, but also there with other streamer.
After Stream went live the webhook says its been there since 2h or smth.
![grafik](https://user-images.githubusercontent.com/8904984/165350486-96adaef0-a41e-4caf-9721-ea1446e48081.png)

**Comment by MrBrax** [comment]
if you expand the advanced stuff with the + button, what does the "went live" say?
it's a bit odd considering the webhook duration is calculated with the start and end capture time

**Comment by Serph91P** [comment]
> 

thats what I thought and thats also why I created that issue. almost like its running in the background or smth:  
![grafik](https://user-images.githubusercontent.com/8904984/165352557-17b1a073-e037-4950-9e58-3c6db91c6a56.png)

**Comment by Serph91P** [comment]
> 

ok maybe you are right:  
![grafik](https://user-images.githubusercontent.com/8904984/165353448-c0f6bdfa-7874-4aaf-99b7-fe4fbadb0acc.png)

**Comment by MrBrax** [comment]
and as usual, working with dates and especially timezones in js is a nightmare
