### ISSUE TITLE
Crontabs in docker/alpine

### ISSUE THREAD

**Issue by MrBrax** [MrBrax/TwitchAutomator#15]
There doesn't seem to be any elegant solutions to this, so i'll leave it completely manual until docker support is more mature.

**Comment by KurtzPT** [comment]
Have you checked this? https://stackoverflow.com/questions/36453787/failed-to-edit-crontab-linux-alpine ?

**Comment by KurtzPT** [comment]
Related to it, I found out [this](https://gist.github.com/alesk/33b716f04cdce0751473b8232405dc32), unfortunately I can't test it out since I don't know how to create docker images myself with these changes.

**Comment by MrBrax** [comment]
yes, that's what i don't find elegant, i don't even have an entrypoint right now

**Comment by MrBrax** [comment]
a separate cron container seems to work, but pushing multiple containers/compose seems to be at a very early stage

**Comment by KurtzPT** [comment]
> a separate cron container seems to work, but pushing multiple containers/compose seems to be at a very early stage

Just set-up the multiple containers with docker compose, will check it out

**Comment by KurtzPT** [comment]
I forgot to give feedback, it is working fine.

**Comment by danyal** [comment]
@KurtzPT So cron is working when using the dockerhub image?

**Comment by KurtzPT** [comment]
@danyal I didn't use the dockerhub image, I build it myself with docker compose, so I don't know. But according to @MrBrax on the front page:

> Docker hub doesn't seem to fully support docker-compose apps, so the cron stuff won't work.

**Comment by danyal** [comment]
@KurtzPT Ah ok. I'm a Docker novice and was wondering if you could give me some info on how to build manually? I can get this working via the hub image but not build. Where do I need to run the build command and what files need to be in that dir besides the docker-compose? Do I pull the git repo first?
