### ISSUE TITLE
FastCGI sent in stderr: "PHP message: PHP Notice:  Array to string conversion in (..)

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/TwitchAutomator#16]
**Error:**

> NOTICE: PHP message: PHP Notice:  Array to string conversion in /var/www/twitchautomator/cache/twig/ae/ae5e745ff4f4edb545662f7365b5c391b748e2a9a9af4db48635c780db5f9d3e.php on line 52
> 2020/12/22 13:27:20 [error] 43#43: *538 FastCGI sent in stderr: "PHP message: PHP Notice:  Array to string conversion in /var/www/twitchautomator/cache/twig/ae/ae5e745ff4f4edb545662f7365b5c391b748e2a9a9af4db48635c780db5f9d3e.php on line 52PHP message: PHP Notice:  Array to string conversion in /var/www/twitchautomator/cache/twig/ae/ae5e745ff4f4edb545662f7365b5c391b748e2a9a9af4db48635c780db5f9d3e.php on line 52PHP message: PHP Notice:  Array to string conversion in /var/www/twitchautomator/cache/twig/ae/ae5e745ff4f4edb545662f7365b5c391b748e2a9a9af4db48635c780db5f9d3e.php on line 52PHP message: PHP Notice:  Array to string conversion in /var/www/twitchautomator/cache/twig/ae/ae5e745ff4f4edb545662f7365b5c391b748e2a9a9af4db48635c780db5f9d3e.php on line 52PHP message: PHP Notice:  Array to string conversion in /var/www/twitchautomator/cache/twig/ae/ae5e745ff4f4edb545662f7365b5c391b748e2a9a9af4db48635c780db5f9d3e.php on line 52PHP message: PHP Notice:  Array to string conversion in /var/www/twitchautomator/cache/twig/ae/ae5e745ff4f4edb545662f7365b5c391b748e2a9a9af4db48635c780db5f9d3e.php on line 52PHP message: PHP Notice:  Array to string conversion in /var/www/twitchautomator/cache/twig/ae/ae5e745ff4f4edb545662f7365b5c391b748e2a9a9af4db48635c780db5f9d3e.php on line 52PHP message: PHP Notice:  Array to string conversion in /var/www/twitchautomator/cache/twig/ae/ae5e745ff4f4edb545662f7365b5c391b748e2a9a9af4db48635c780db5f9d3e.php on line 52PHP message: PHP Notice:  Array to string conversion in /var/www/twitchautomator/cache/twig/ae/ae5e745ff4f4edb545662f7365b5c391b748e2a9a9af4db48635c780db5f9d3e.php on line 52PHP message: PHP Notice:  Array to string conversion in /var/www/twitchautomator/cache/twig/ae/ae5e745ff4f4edb545662f7365b5c391b748e2a9a9af4db48635c780db5f9d3e.php on line 52PHP message: PHP Notice:  Array to string conversion in /var/www/twitchautomator/cache/twig/ae/ae5e745ff4f4edb545662f7365b5c391b748e2a9a9af4db48635c780db5f9d3e.php on line 52PHP message: PHP Notice:  Array to string conversion in /var/www/twi

I've noticed multiple errors while recording streams of an Array to string conversion in .php files inside the twig folder. I opened up one of these files and the function where the error appears is the following:

````
protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        // line 1
        echo "<div class=\"log_viewer\">
    ";
        // line 19
        echo "    <table>
        ";
        // line 20
        $context['_parent'] = $context;
        $context['_seq'] = twig_ensure_traversable(($context["log_lines"] ?? null));
        foreach ($context['_seq'] as $context["_key"] => $context["line"]) {
            // line 21
            echo "            <tr class=\"log_";
            echo twig_escape_filter($this->env, twig_lower_filter($this->env, twig_get_attribute($this->env, $this->source, $context["line"], "level", [], "any", false, false, false, 21)), "html", null, true);
            echo "\"";
            if (twig_get_attribute($this->env, $this->source, ($context["config"] ?? null), "debug", [], "any", false, false, false, 21)) {
                echo " title=\"";
                **echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["line"], "metadata", [], "any", false, false, false, 21), "html", null, true);
                echo "\"";**
            }
            echo ">
                <td>";
            // line 22
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["line"], "date_string", [], "any", false, false, false, 22), "html", null, true);
            echo "</td>
                <td><a href=\"javascript:filterLog('";
            // line 23
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["line"], "module", [], "any", false, false, false, 23), "html", null, true);
            echo "');\">";
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["line"], "module", [], "any", false, false, false, 23), "html", null, true);
            echo "</a></td>
                <td>";
            // line 24
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["line"], "level", [], "any", false, false, false, 24), "html", null, true);
            echo "</td>
                <td>";
            // line 25
            echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["line"], "text", [], "any", false, false, false, 25), "html", null, true);
            echo "</td>
            </tr>
        ";
        }
        $_parent = $context['_parent'];
        unset($context['_seq'], $context['_iterated'], $context['_key'], $context['line'], $context['_parent'], $context['loop']);
        $context = array_intersect_key($context, $_parent) + $_parent;
        // line 28
        echo "    </table>
</div>";
    }
````

The line of the error in question is the following, after the comment "line 21" inside the "if":
`                echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, $context["line"], "metadata", [], "any", false, false, false, 21), "html", null, true);`

**Comment by MrBrax** [comment]
that should only happen if you have debug mode turned on, seems that i forgot to serialise it

**Comment by KurtzPT** [comment]
> that should only happen if you have debug mode turned on, seems that i forgot to serialise it

I had turned on to debug other errors I reported indeed.
