### ISSUE TITLE
option to start capture of already live channels when container is started

### ISSUE THREAD

**Issue by MadZeh** [MrBrax/TwitchAutomator#160]
Is there a reliable possibillity to start capturing a stream even when the channel was online before TwitchAutomator was started?

**Comment by MrBrax** [comment]
nope, chapter offsets and all that would probably be all wrong too
i did have such a feature in the php server, but all it did was mock a fake payload to the hook

**Comment by MrBrax** [comment]
i could reimplement it, but i would advise against using it, as it could cause all sorts of trouble

**Comment by MadZeh** [comment]
It would be enough for me to capture only the VOD in this case without any additional infos or chat so it shouldn't mess up everything.

**Comment by MrBrax** [comment]
are you going to use it more than once? why not just add the channel in beforehand?

**Comment by MadZeh** [comment]
I would use it for channels that doesn't use vods so i can "rescue" the missed part of the stream to view it later when TwitchAutomator crashed unexpected or whatever.

**Comment by MadZeh** [comment]
solution for now is using additional streamlink independent of this great piece of work :)

**Comment by MrBrax** [comment]
> I would use it for channels that doesn't use vods so i can "rescue" the missed part of the stream to view it later when TwitchAutomator crashed unexpected or whatever.

if you added the channel before they went live, it will record the stream regardless of if they have vods enabled or not

**Comment by MadZeh** [comment]
But it will not begin to record the stream, if it was live before TwitchAutomator was started.

**Comment by MrBrax** [comment]
are you turning it on just when you need to record something? probably not the most suitable program for that
