### ISSUE TITLE
websocket errors.

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/TwitchAutomator#164]
TwitchAutomatorTS 0.1.2/0.7.8-a

Having a disconnect red box in the bottom right corner, I don't remember seeing this before.

![image](https://user-images.githubusercontent.com/14930057/166058888-8eb6b224-bc0b-46f4-a09e-165af3f706ce.png)

**Comment by MrBrax** [comment]
is the generated url you blurred making sense for the domain you're using it on? i don't think i changed anything recently, unless you haven't updated in a while

**Comment by KurtzPT** [comment]
Yes its my domain. I don't think it I had this before, but I can't be 100% sure.

**Comment by MrBrax** [comment]
are you using a reverse proxy in front of it? did you use the websocket before this? like it said connected instead of "updating 1" or whatever?

**Comment by KurtzPT** [comment]
> are you using a reverse proxy in front of it? did you use the websocket before this? like it said connected instead of "updating 1" or whatever?

I never used websocket before, but it's turned on by default on settings and I didn't change it. And yes there's a reverse proxy in front of it.

**Comment by MrBrax** [comment]
that makes sense, i'll probably reimplement the old ticker to be global, but i recommend using the websocket anyway since it just updates when it needs to

you'll need to set the http upgrade and proxypass stuff depending on what reverse proxy server you're using

```
location ~ /socket/ {
        proxy_pass https://docker-ip:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Y-Real-IP $realip_remote_addr;
}
```

**Comment by KurtzPT** [comment]
That worked, it's now "connected". Probably I never noticed the disconnected red box before.

**Comment by KurtzPT** [comment]
But I do have this message in the console:

![image](https://user-images.githubusercontent.com/14930057/166064387-a966062f-462d-45a5-90f8-659be12deb20.png)

**Comment by MrBrax** [comment]
that's fine, just me being lazy not having added a handler for that one yet

**Comment by KurtzPT** [comment]
Gotcha. All good then, closing it.
