### ISSUE TITLE
audio_only is missing in quality list

### ISSUE THREAD

**Issue by mr-flibble** [MrBrax/TwitchAutomator#166]
Hello, I just testing latest version  0.1.2 / 0.7.9 and i noticed that I can't add **audio_only** quality for channel. It seems not to be among the allowed options.
Is possible to allow it? Thanks

![image](https://user-images.githubusercontent.com/5197625/166122646-cc3d4b09-850d-45d6-9539-79b4cbb9ee66.png)

**Comment by MrBrax** [comment]
true, i think i had this as an option a while back

i'll add it, not sure what the consequences of it not having video will be though

**Comment by mr-flibble** [comment]
Thanks, I will test it and report back.

**Comment by MrBrax** [comment]
one definite thing is that the file will still use ts/mp4 even with just audio, depending on how hardcoded i've made that i might be able to change it

**Comment by MrBrax** [comment]
better support added now, ui conforms to audio only captures, uses m4a instead of video

**Comment by mr-flibble** [comment]
Can confirm that audio_only work

Instead of .aac now is audio_only stored as .m4a - and even with filled tags! (title and artist) 
that's a really big wow :)
Thanks!
