### ISSUE TITLE
Insecure middleware over HTTP.

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/TwitchAutomator#17]
While adding a password and having `Force HTTPS for password` unchecked it didn't work out as I hoped to, I'm still having the following error:

> Slim Application Error
> The application could not run because of the following error:
> 
> Details
> Type: RuntimeException
> Code: 0
> Message: Insecure use of middleware over HTTP denied by configuration.
> File: /var/www/twitchautomator/vendor/tuupola/slim-basic-auth/src/HttpBasicAuthentication.php
> Line: 148

**Comment by MrBrax** [comment]
i'm not sure what else it could be really, `secure` is set to false with the config

**Comment by KurtzPT** [comment]
I couldn't find the reason for it to not work, it seems that it totally ignores that false flag for some reason.

What I did was I edited nginx.conf file to add a new SSL port (8081), added the private key/cert associated with the SSL I have and reloaded nginx. APP URL is now using the http port (8080) and I use the HTTPs 8081, everything seems to be working.

**Comment by MrBrax** [comment]
i would recommend using https whenever you can, especially since letsencrypt issues free certs

**Comment by KurtzPT** [comment]
> i would recommend using https whenever you can, especially since letsencrypt issues free certs

Indeed and its what I'm doing, but I did find it weird that the secure to false did not work for whatever reason.

**Comment by mr-flibble** [comment]
@KurtzPT in my case, this was caused by "_ProxyPreserveHost On_" in apache reverse proxy. Probably because internaly its on http. After turning it off is error gone.

**Comment by KurtzPT** [comment]
@MrBrax with proper reverse proxy with https now installed still having issues with this. Maybe the following can help?

https://github.com/tuupola/slim-basic-auth#allow-https-termination-and-forwarding

I have to set the `Force HTTPS for password` off to add a password since internally its using http only

**Comment by KurtzPT** [comment]
@MrBrax it seems the secure flag is not being properly set to false.

I changed this line on public.php:
`"secure" => TwitchConfig::cfg('password_secure', true) == true,`
to
`"secure" => false,`

and now it asks for password without any problem.

**Comment by MrBrax** [comment]
Is it set to false in the config page? Can't really return true otherwise

**Comment by KurtzPT** [comment]
> Is it set to false in the config page? Can't really return true otherwise

Yes, I even went to config.json and its set to false:

![image](https://user-images.githubusercontent.com/14930057/151666573-952dcd58-5f7c-4066-8ac3-a073b6dc2751.png)

**Comment by MrBrax** [comment]
Very strange indeed, this is probably why i should learn how to set up proper tests

**Comment by KurtzPT** [comment]
I'm not a PHP guy but this seems to be working:

![image](https://user-images.githubusercontent.com/14930057/151667476-cc9fcacd-fc40-4118-82d0-33179c805370.png)

If I have password_secure set as false, it asks me for password (correct behavior) if it's set to true it gives me the insecure error (also "correct" behavior since internally with reverse proxy I'm using http)

**Comment by MrBrax** [comment]
true should be the default, only forceable to off. so it's inverted?

**Comment by MrBrax** [comment]
i updated the composer packages, it might have been a bug in slim/psr7

**Comment by KurtzPT** [comment]
> i updated the composer packages, it might have been a bug in slim/psr7

Tried out now, it's giving the same issue.

**Comment by MrBrax** [comment]
Maybe it's just intentional then, it's supposed to be set inverse?

**Comment by KurtzPT** [comment]
It's not inverse, unless I'm not understanding what you mean be inverse here. If `password_secure` is set to false on the configs, secure is set to false with my solution.

Without my solution is always true, doesn't matter what the `password_secure` is set to. Feels like it's always using the default secure value which I assume is `true`.

**Comment by MrBrax** [comment]
I think i found the issue now, removed the duplicate empty value check for the cfg function

**Comment by KurtzPT** [comment]
It's fixed! Finally I can close this almost 2 year issue ! 🥳

**Comment by MrBrax** [comment]
amazing

**Comment by KurtzPT** [comment]
Thanks again for the help on both issues I raised since yesterday @MrBrax :)

**Comment by MrBrax** [comment]
good stuff, hopefully it won't break anything

**Comment by MrBrax** [comment]
i think i found the first issue, if you had timezone set it seems to have reset the eventsub secret somehow

**Comment by KurtzPT** [comment]
My timezone is set to the default one and my `eventsub_secret` is still set (not sure if it reseted or not)

**Comment by MrBrax** [comment]
alright good, might have been some earlier testing error then

**Comment by KurtzPT** [comment]
> alright good, might have been some earlier testing error then
> 
> if the hooks don't fire when streams happen this is the cause

I set some channels and its already recording one when it came live so everything seems fine for now.
