### ISSUE TITLE
More setting issues

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/TwitchAutomator#171]
Saving settings automatically set at least these as true:

![image](https://user-images.githubusercontent.com/14930057/166157887-e123289a-befa-4fef-8917-7d2fae7e332d.png)

EDIT: Actually it sets every single checkbox in all settings as true.

**Comment by KurtzPT** [comment]
Even when I try to uncheck and save the settings, it doesn't matter it keeps them checked.

**Comment by MrBrax** [comment]
i guess that's what i guess by trying to move everything to json
