### ISSUE TITLE
[feature request] deactivate "auto"-capture of channels temporarily

### ISSUE THREAD

**Issue by MadZeh** [MrBrax/TwitchAutomator#173]
option to grey out channels in list and temporarily disable the autocapture of this channel till I wanna capture it again.

**Comment by MrBrax** [comment]
"No capture" in the channel config does this, unless I'm misinterpreting this?

**Comment by MadZeh** [comment]
Sry for empty text, missclicked on the enterbutton on my keyboard accidently.

and sorry, that I was so blind to see that the option is already available. i feel stupid now  :D
