### ISSUE TITLE
Failed to spawn process for chatdump

### ISSUE THREAD

**Issue by CappiSteijns** [MrBrax/TwitchAutomator#177]
Hi!

I am using TwitchAutomator as a docker container on Unraid. 

Unfortunatly I can't figure out how to save live chat. I get the following error:

![afbeelding](https://user-images.githubusercontent.com/84481241/166467229-084561ec-9832-40c3-bf9b-6b0b44f53206.png)

These are the options I am using:
![afbeelding](https://user-images.githubusercontent.com/84481241/166467370-b20d369b-5c6a-493a-8580-a68c745b62ac.png)
![afbeelding](https://user-images.githubusercontent.com/84481241/166467462-3fcc76a4-5752-464e-b49a-b25c9b19df2d.png)
![afbeelding](https://user-images.githubusercontent.com/84481241/166467665-266f5f34-6f5b-4253-970f-aaebbd73f05d.png)

Adding Log if needed:
[2022-05-03.log](https://github.com/MrBrax/TwitchAutomator/files/8610932/2022-05-03.log)
[capture_egbertlive_2022-05-03T13_08_14Z_39360334152_stdout.log](https://github.com/MrBrax/TwitchAutomator/files/8610940/capture_egbertlive_2022-05-03T13_08_14Z_39360334152_stdout.log)

**Comment by CappiSteijns** [comment]
> the chatdump_ software log files would probably show the error here

It doesn't seem those logs are created. Searched in every directory.

This is the Logs folder:
![afbeelding](https://user-images.githubusercontent.com/84481241/166477684-ed9b47ab-a96a-4178-afa9-8eba16822d29.png)

Maybe there is a chance some logs are over here but I cant find the right environment options to enable this:
![afbeelding](https://user-images.githubusercontent.com/84481241/166477978-99c964cc-6e96-4ab4-abf3-560036235c16.png)

Trying the following to enable but it won't make any changes:
![afbeelding](https://user-images.githubusercontent.com/84481241/166478241-7392fdcf-8372-49ae-9301-319165355deb.png)
![afbeelding](https://user-images.githubusercontent.com/84481241/166478300-bcd771dd-2f30-40de-b70b-e49fc0be8c77.png)

**Comment by MrBrax** [comment]
the value needs to be exactly `1` for that to work, and you need the other one near the bottom of the readme too
you should be able to browse all the logs in the data folder however

are there any console errors in the docker container? if there were no logs saved, there might be a stack trace in there

**Comment by CappiSteijns** [comment]
Got this section to work tho, thanks :) But it won't show any more then in the directory's:
![afbeelding](https://user-images.githubusercontent.com/84481241/166482382-24a93eb0-069f-4f05-b50e-6c064629b5c2.png)

**Comment by MrBrax** [comment]
quite odd though unless nobody else has this issue too? i thought docker would be the same for everyone

**Comment by MrBrax** [comment]
seems like the original package https://github.com/KararTY/dank-twitch-irc is abandoned, could be difficult finding a good replacement

**Comment by CappiSteijns** [comment]
> 

Ahh, thats to bad!! But thanks for the help and info!

**Comment by MrBrax** [comment]
considering it works for me and probably everyone else though is really weird

**Comment by CappiSteijns** [comment]
> 

ahh, good to hear it does work then, I will try to mess arround more and see if I can find something that might help.

**Comment by KurtzPT** [comment]
I can try out and test a stream with that setting turned on (all my streams don't have that turned on)

**Comment by dabenzel** [comment]
I have the same problem - also Unraid

**Comment by MrBrax** [comment]
does dumping a chat via the new tools section also error?

**Comment by MrBrax** [comment]
confirmed broken in docker

**Comment by KurtzPT** [comment]
Same issue here.

**Comment by MrBrax** [comment]
figured it out
