### ISSUE TITLE
[feature request] Download Clips

### ISSUE THREAD

**Issue by dabenzel** [MrBrax/TwitchAutomator#181]
Hi!
Since there is a clips folder, I think you had the Idea, but I want to ask it neverthenless.

Is it possible to download Clips in the future?
That would be really nice

**Comment by MrBrax** [comment]
true, that does seem like a pretty obvious feature

**Comment by MrBrax** [comment]
haven't come up with a good filename yet, but seems to be working

**Comment by dabenzel** [comment]
Looks good and works on my end!

Thank you sir! Really good work in the last days!

**Comment by MrBrax** [comment]
added more metadata and quality setting

**Comment by dabenzel** [comment]
hi!
Sorry to reopen, can you shorten the filename a little bit, like `<clip_name>-<channel_name>.mp4`
Yesterday evening I had a clip with a very long title

**Comment by MrBrax** [comment]
> hi! Sorry to reopen, can you shorten the filename a little bit, like `<clip_name>-<channel_name>.mp4` Yesterday evening I had a clip with a very long title


https://user-images.githubusercontent.com/1517911/166981839-25ce0356-b436-48af-8937-42ad6197ba57.mp4

i always wanted to do something with string formatting, this might have been the perfect time

**Comment by dabenzel** [comment]
Very nice!
But can you save the last entered pattern?

**Comment by MrBrax** [comment]
it will use whatever pattern you put in, yes? or do you mean like a history of all of them?

**Comment by dabenzel** [comment]
no, only the last one i put in there. That i dont have to redo it every time.

in my version from yesterday evening, you only support
`https://www.twitch.tv/<channel>/clip/<clipid>` and not `https://clips.twitch.tv/<clipid>` - can that also be added?

Can people also have the option to re-open issues here?

**Comment by MrBrax** [comment]
it's a setting in the config menu so it's permanently saved

i think i added it in the second update https://github.com/MrBrax/TwitchAutomator/blob/ffc44480aa470a0bf7fdd5f9454a66ecac9cfc97/server/src/Core/TwitchVOD.ts#L2640

doesn't seem possible if i closed it myself. i do get emails still though, so only a problem for newcomers i guess?
