### ISSUE TITLE
docker-compose question

### ISSUE THREAD

**Issue by mr-flibble** [MrBrax/TwitchAutomator#190]
Hello, I'm a little confused about the current https://github.com/MrBrax/TwitchAutomator/blob/master/docker-compose.yml file
I'm running docker-compose version and it's works (with building after every git update)
But I started getting error messages from [watchtower](https://github.com/containrrr/watchtower)
```
Could not do a head request for "mrbrax/twitchautomator:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"
Unable to update container "/twitchautomator-web-1": Error response from daemon: manifest for mrbrax/twitchautomator:latest not found: manifest unknown: manifest unknown. Proceeding to next.
```

Maybe there is an incorrect name in the docker-compose file?
At [hub.docker](https://hub.docker.com/r/mrbrax/twitchautomator/tags) I see tag: _mrbrax/twitchautomator:master_

Maybe is should be _master_ also in docker-compose?

**Comment by MrBrax** [comment]
yes, when i made github actions push docker images it started using master
