### ISSUE TITLE
Using Archive function give a timeout message and copy incomplete vods

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/TwitchAutomator#20]
As the title says, I just used the archive function on 4 streams that were recorded and for each one the page kept on "loading" till it gives an timeout (but the file is correctly archived).

> 2020/12/29 21:45:08 [error] 42#42: *5914 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.18.0.1, server: _, request: &quot;GET /api/v0/vod/OuterHeaven_2020-12-23T02_19_40Z_40452534668/save HTTP/1.1&quot;, upstream: &quot;fastcgi://127.0.0.1:9000&quot;, host: &quot;redacted&quot;

EDIT: I just checked and the files copied to saved_vods are incomplete, so the timeout actually impacts the files.

**Comment by MrBrax** [comment]
oh yeah true, never thought about it timing out, especially on hard drives
