### ISSUE TITLE
/subs error with last code.

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/TwitchAutomator#21]
Another error when going to /subs (with the last commit available):

> [error] 42#42: *323 FastCGI sent in stderr: &quot;PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to App\TwitchHelper::getChannelData() must be of the type string, bool given, called in /var/www/twitchautomator/src/Controller/SubController.php on line 68 and defined in /var/www/twitchautomator/src/TwitchHelper.php:388

**Comment by KurtzPT** [comment]
IIRC, this happens when the oauth is not correct, somewhere in the code it returns a boolean.

**Comment by MrBrax** [comment]
i think i fixed this
