### ISSUE TITLE
When saving in settings getting error

### ISSUE THREAD

**Issue by danyal** [MrBrax/TwitchAutomator#22]
I've successfully been able to run the docker image but when I try to save app url or anything else in settings I'm getting this error: External app url could be contacted at all (http://localhost:8081/hook).

**Comment by danyal** [comment]
Figured it out. It needs the internal port # (8080).

**Comment by MrBrax** [comment]
it needs to be the external app url, otherwise twitch won't know where to send data

**Comment by danyal** [comment]
I've built the docker image manually and exposed the server externally. Verified that the server is externally accessible etc. I've filled out all the required info in Settings > Basic & Binaries

Few issues I'm running into:
1. After adding 1 streamer, I cannot delete or save. It says "streamer not found". This doesn't happen for the 2nd or more streamers.
2. After adding streamers, recording never starts. I'm adding streamers that are already streaming and I'm assuming it should start recording immediately?

**Comment by MrBrax** [comment]
please make a new issue when it's unrelated

1. i have to test this
2. no, it only starts recording when they go live, otherwise you can use the force record button, which isn't recommended.
3. seems that something is wrong with your dns/network setup

**Comment by danyal** [comment]
To update the image, do I just do a git pull and then run docker-compose up --build -d again?

**Comment by MrBrax** [comment]
correct
