### ISSUE TITLE
Streamers are being captured after being deleted

### ISSUE THREAD

**Issue by Zulux91** [MrBrax/TwitchAutomator#23]
I went to check my setup and found that it was capturing a streamer that I previously had (until yesterday) but is not in my current list. When I removed said streamer got a green successful message and the log clearly says:
`Calling unsubscribe for Mizzy`
`SUCCESS Sent unsubscribe request for Mizzy (96940137)`
`SUCCESS Received hub challenge from twitch for userid Mizzy (96940137) when trying to unsubscribe`
`SUCCESS Successfully unsubscribed to userid 96940137 (Mizzy) on twitch`

So since it is recording an unsubscribed streamer I checked my streamersv2.json and that streamer (along others I deleted) is still there.

My current setup is the docker image up to date with yesterdays' commits and a ngrok tunnel to get the hooks, Everything works great except for the phantom streamers.

**Comment by MrBrax** [comment]
the streamers_v2.json file is just for caching the user data, the config is in the config directory.

**Comment by Zulux91** [comment]
The streamer being captured is not in my config.json from the config directory.

**Comment by MrBrax** [comment]
what does the /subs page show? there was another user with a similar problem, it could be twitch still sending out webhooks to unsubscribed endpoints

**Comment by Zulux91** [comment]
It shows the only two streamers that I'm watching, the same two that my dashboard shows.

**Comment by MrBrax** [comment]
i unsubbed from a streamer a couple days ago and i don't have that problem, i really don't know what to tell you

**Comment by MrBrax** [comment]
have you changed the api keys or the app url afterwards?

**Comment by Zulux91** [comment]
No, I haven't done anything besides deleting that streamer and some others.

**Comment by MrBrax** [comment]
if they don't show up on the /subs page i really don't know what it could be

the subs will eventually run out, or you could try the instance feature and re-sub, if it actually works

**Comment by Zulux91** [comment]
I guess I'll wait until the sub runs out. Thanks for the support. 👍

**Comment by MrBrax** [comment]
subbed to a streamer yesterday and deleted afterwards, it's not shown in the subs page, and they went online just now and it's not capturing, so it seems that for some users it lingers, very strange
