### ISSUE TITLE
crontab and password protected turned on with docker-compose fails.

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/TwitchAutomator#27]
Crontab will not work if we have TwitchAutomator password protected (I failed to notice this until the subscriptions expired and crontab failed to renew them)

Example:

> 172.18.0.2 - - [09/Jan/2021:12:00:00 +0000] "GET /cron/check_muted_vods HTTP/1.1" 500 5 "-" "curl/7.69.1" "-" 0.010 0.011 . -
> NOTICE: PHP message: PHP Fatal error:  Uncaught RuntimeException: Insecure use of middleware over HTTP denied by configuration. in /var/www/twitchautomator/vendor/tuupola/slim-basic-auth/src/HttpBasicAuthentication.php:148

Maybe make the private IP range 172 an exception to use password?

I also noticed the crontab uses the path "cron/sub" while the exception on the security side is just "/sub"

**Comment by MrBrax** [comment]
i'll change it, but i'm currently working on a big ui overhaul which removes pretty much every single regular page and endpoint, everything needs to be changed when upgrading.

you can try it out by downloading the develop branch: https://github.com/MrBrax/TwitchAutomator/tree/develop

**Comment by KurtzPT** [comment]
I'll spun a new docker instance and try out that new development version sometime soon 👍

**Comment by MrBrax** [comment]
i can't find a good way of packaging builds, making them manually sounds like a pain

**Comment by KurtzPT** [comment]
This seems to be fixed at least with the new version:

![image](https://user-images.githubusercontent.com/14930057/107132853-c740bd00-68da-11eb-8b3d-cde5b4fa6189.png)

**Comment by MrBrax** [comment]
yeah, all api endpoints have changed pretty much, gotta make sure all of them are correct now

**Comment by KurtzPT** [comment]
![image](https://user-images.githubusercontent.com/14930057/107350818-d0d84980-6ac1-11eb-8678-9a8645b2433d.png)

From the above, it seems just the dump_playlists is not working. 

I also noticed that the url might be different? The crontab example says "playlist_dump" and not "dump_playlists"

![image](https://user-images.githubusercontent.com/14930057/107351184-36c4d100-6ac2-11eb-9c00-82d437b2cd67.png)

**Comment by MrBrax** [comment]
doesn't surprise me, experimental feature that i barely worked on and confused the name of, i'll have to make up a plan for all the names and such

**Comment by MrBrax** [comment]
also, the docker crontab doesn't run the playlist dump thing by default

**Comment by MrBrax** [comment]
should be fixed by now i think, and i've managed to find a way to pull the entire webapp from the hub, instructions are in the readme
