### ISSUE TITLE
HTTP 500 when running with Docker

### ISSUE THREAD

**Issue by ctlaltdefeat** [MrBrax/TwitchAutomator#35]
When using docker (both the Dockerhub version and a manual build) the web container throws up an HTTP 500 error at port 8082, and the logs directory is empty.
Running `docker logs` on the container gives:
```
NOTICE: PHP message: Saving config failed, permissions issue?
NOTICE: PHP message: PHP Warning:  fopen(/var/www/twitchautomator/src/../logs/2021-03-01.log): failed to open stream: Permission denied in /var/www/twitchautomator/src/TwitchHelper.php on line 326
2021-03-01 17:06:18.267 | config | <FATAL> Saving config failed, permissions issue?
2021/03/01 17:06:18 [error] 9#9: *77 FastCGI sent in stderr: "PHP message: Saving config failed, permissions issue?PHP message: PHP Warning:  fopen(/var/www/twitchautomator/src/../logs/2021-03-01.log): failed
to open stream: Permission denied in /var/www/twitchautomator/src/TwitchHelper.php on line 326PHP message: PHP Fatal error:  Uncaught TypeError: fwrite() expects parameter 1 to be resource, bool given in /var/
www/twitchautomator/src/TwitchHelper.php:327
Stack trace:
#0 /var/www/twitchautomator/src/TwitchHelper.php(327): fwrite()
#1 /var/www/twitchautomator/src/TwitchConfig.php(203): App\TwitchHelper::logAdvanced()
#2 /var/www/twitchautomator/src/TwitchConfig.php(234): App\TwitchConfig::saveConfig()
#3 /var/www/twitchautomator/src/TwitchConfig.php(162): App\TwitchConfig::generateConfig()
#4 /var/www/twitchautomator/src/TwitchConfig.php(265): App\TwitchConfig::loadConfig()
#5 /var/www/twitchautomator/vendor/composer/ClassLoader.php(478): include('/var/www/twitch...')
#6 /var/www/twitchautomator/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#8 /var/www/twitchautomator/src/TwitchHelper.php(1159): spl_autoload_call()
#9 /var/www/twitchautomator/vendor/composer/ClassLoader.php(478): include('/var/www/twitc" while reading response header from upstream, client: 172.18.0.1, server: _, request: "HEAD / HTTP/1.1", upstream: "fas
tcgi://127.0.0.1:9000", host: "localhost:8082"
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: fwrite() expects parameter 1 to be resource, bool given in /var/www/twitchautomator/src/TwitchHelper.php:327
Stack trace:
#0 /var/www/twitchautomator/src/TwitchHelper.php(327): fwrite()
#1 /var/www/twitchautomator/src/TwitchConfig.php(203): App\TwitchHelper::logAdvanced()
#2 /var/www/twitchautomator/src/TwitchConfig.php(234): App\TwitchConfig::saveConfig()
#3 /var/www/twitchautomator/src/TwitchConfig.php(162): App\TwitchConfig::generateConfig()
#4 /var/www/twitchautomator/src/TwitchConfig.php(265): App\TwitchConfig::loadConfig()
#5 /var/www/twitchautomator/vendor/composer/ClassLoader.php(478): include('/var/www/twitch...')
#6 /var/www/twitchautomator/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#8 /var/www/twitchautomator/src/TwitchHelper.php(1159): spl_autoload_call()
#9 /var/www/twitchautomator/vendor/composer/ClassLoader.php(478): include('/var/www/twitc...
172.18.0.1 - - [01/Mar/2021:17:06:18 +0000] "HEAD / HTTP/1.1" 500 0 "-" "curl/7.70.0" "-" 0.004 0.003 . -
```

**Comment by MrBrax** [comment]
you should probably fix your permissions then?

**Comment by ctlaltdefeat** [comment]
My bad, I thought that the directories causing the issue were internal container files but I see they're volume mounts.

**Comment by wiiarctus** [comment]
Hello, I have exactly the same problem... Is there any way to get it fixed? Thanks in advance!

**Comment by MrBrax** [comment]
> 
> 
> Hello, I have exactly the same problem... Is there any way to get it fixed? Thanks in advance!

did you check your permissions or the error logs?

**Comment by wiiarctus** [comment]
> > Hello, I have exactly the same problem... Is there any way to get it fixed? Thanks in advance!
> 
> did you check your permissions or the error logs?

Hey, I don't really know how to fix the permissions inside the container but I did ran `docker logs twitchautomator_web_1` and got this:

`2021-04-26 18:11:08,093 INFO supervisord started with pid 1
2021-04-26 18:11:09,096 INFO spawned: 'nginx' with pid 8
2021-04-26 18:11:09,098 INFO spawned: 'php-fpm' with pid 9
[26-Apr-2021 18:11:09] NOTICE: fpm is running, pid 9
[26-Apr-2021 18:11:09] NOTICE: ready to handle connections
2021-04-26 18:11:10,552 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 18:11:10,552 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
NOTICE: PHP message: Saving config failed, permissions issue?
NOTICE: PHP message: PHP Warning:  fopen(/var/www/twitchautomator/src/../logs/2021-04-26.log): failed to open stream: Permission denied in /var/www/twitchautomator/src/TwitchHelper.php on line 338
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: fwrite() expects parameter 1 to be resource, bool given in /var/www/twitchautomator/src/TwitchHelper.php:339
2021/04/26 18:11:15 [error] 10#10: *1 FastCGI sent in stderr: "PHP message: Saving config failed, permissions issue?PHP message: PHP Warning:  fopen(/var/www/twitchautomator/src/../logs/2021-04-26.log): failed to open stream: Permission denied in /var/www/twitchautomator/src/TwitchHelper.php on line 338PHP message: PHP Fatal error:  Uncaught TypeError: fwrite() expects parameter 1 to be resource, bool given in /var/www/twitchautomator/src/TwitchHelper.php:339
Stack trace:
#0 /var/www/twitchautomator/src/TwitchHelper.php(339): fwrite()
#1 /var/www/twitchautomator/src/TwitchConfig.php(203): App\TwitchHelper::logAdvanced()
#2 /var/www/twitchautomator/src/TwitchConfig.php(234): App\TwitchConfig::saveConfig()
#3 /var/www/twitchautomator/src/TwitchConfig.php(162): App\TwitchConfig::generateConfig()
#4 /var/www/twitchautomator/src/TwitchConfig.php(265): App\TwitchConfig::loadConfig()
#5 /var/www/twitchautomator/vendor/composer/ClassLoader.php(476): include('/var/www/twitch...')
#6 /var/www/twitchautomator/vendor/composer/ClassLoader.php(344): Composer\Autoload\includeFile()
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#8 /var/www/twitchautomator/src/TwitchHelper.php(1172): spl_autoload_call()
#9 /var/www/twitchautomator/vendor/composer/ClassLoader.php(476): include('/var/www/twitc" while reading response header from upstream, client: 172.21.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:8082"
Stack trace:
#0 /var/www/twitchautomator/src/TwitchHelper.php(339): fwrite()
#1 /var/www/twitchautomator/src/TwitchConfig.php(203): App\TwitchHelper::logAdvanced()
#2 /var/www/twitchautomator/src/TwitchConfig.php(234): App\TwitchConfig::saveConfig()
#3 /var/www/twitchautomator/src/TwitchConfig.php(162): App\TwitchConfig::generateConfig()
#4 /var/www/twitchautomator/src/TwitchConfig.php(265): App\TwitchConfig::loadConfig()
#5 /var/www/twitchautomator/vendor/composer/ClassLoader.php(476): include('/var/www/twitch...')
#6 /var/www/twitchautomator/vendor/composer/ClassLoader.php(344): Composer\Autoload\includeFile()
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#8 /var/www/twitchautomator/src/TwitchHelper.php(1172): spl_autoload_call()
#9 /var/www/twitchautomator/vendor/composer/ClassLoader.php(476): include('/var/www/twitc...
2021-04-26 18:11:15.681 | config | <FATAL> Saving config failed, permissions issue?
172.21.0.1 - - [26/Apr/2021:18:11:15 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" "-" 0.102 0.104 . -
172.21.0.1 - - [26/Apr/2021:18:11:16 +0000] "GET /favicon.ico HTTP/1.1" 200 15086 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" "-" 0.000 - . -
NOTICE: PHP message: Saving config failed, permissions issue?
2021/04/26 18:11:24 [error] 10#10: *3 FastCGI sent in stderr: "PHP message: Saving config failed, permissions issue?PHP message: PHP Warning:  fopen(/var/www/twitchautomator/src/../logs/2021-04-26.log): failed to open stream: Permission denied in /var/www/twitchautomator/src/TwitchHelper.php on line 338PHP message: PHP Fatal error:  Uncaught TypeError: fwrite() expects parameter 1 to be resource, bool given in /var/www/twitchautomator/src/TwitchHelper.php:339
Stack trace:
#0 /var/www/twitchautomator/src/TwitchHelper.php(339): fwrite()
#1 /var/www/twitchautomator/src/TwitchConfig.php(203): App\TwitchHelper::logAdvanced()
#2 /var/www/twitchautomator/src/TwitchConfig.php(234): App\TwitchConfig::saveConfig()
#3 /var/www/twitchautomator/src/TwitchConfig.php(162): App\TwitchConfig::generateConfig()
#4 /var/www/twitchautomator/src/TwitchConfig.php(265): App\TwitchConfig::loadConfig()
#5 /var/www/twitchautomator/vendor/composer/ClassLoader.php(476): include('/var/www/twitch...')
#6 /var/www/twitchautomator/vendor/composer/ClassLoader.php(344): Composer\Autoload\includeFile()
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#8 /var/www/twitchautomator/src/TwitchHelper.php(1172): spl_autoload_call()
#9 /var/www/twitchautomator/vendor/composer/ClassLoader.php(476): include('/var/www/twitc" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:8082"
NOTICE: PHP message: PHP Warning:  fopen(/var/www/twitchautomator/src/../logs/2021-04-26.log): failed to open stream: Permission denied in /var/www/twitchautomator/src/TwitchHelper.php on line 338
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: fwrite() expects parameter 1 to be resource, bool given in /var/www/twitchautomator/src/TwitchHelper.php:339
Stack trace:
#0 /var/www/twitchautomator/src/TwitchHelper.php(339): fwrite()
#1 /var/www/twitchautomator/src/TwitchConfig.php(203): App\TwitchHelper::logAdvanced()
#2 /var/www/twitchautomator/src/TwitchConfig.php(234): App\TwitchConfig::saveConfig()
#3 /var/www/twitchautomator/src/TwitchConfig.php(162): App\TwitchConfig::generateConfig()
#4 /var/www/twitchautomator/src/TwitchConfig.php(265): App\TwitchConfig::loadConfig()
#5 /var/www/twitchautomator/vendor/composer/ClassLoader.php(476): include('/var/www/twitch...')
#6 /var/www/twitchautomator/vendor/composer/ClassLoader.php(344): Composer\Autoload\includeFile()
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#8 /var/www/twitchautomator/src/TwitchHelper.php(1172): spl_autoload_call()
#9 /var/www/twitchautomator/vendor/composer/ClassLoader.php(476): include('/var/www/twitc...
2021-04-26 18:11:24.350 | config | <FATAL> Saving config failed, permissions issue?`

**Comment by MrBrax** [comment]
Yes, you need to fix your permissions for your setup. The folders affected are in the error messages.
