### ISSUE TITLE
bin_dir issues

### ISSUE THREAD

**Issue by bondurantdt** [MrBrax/TwitchAutomator#4]
Hey there,

Thanks for this work. I installed the required dependencies with pip3 install --user youtube-dl streamlink tcd pipenv and set my bin_dir path to /home/username/.local/lib/python3.8/site-packages but the packages are not detected. I can see on the server they are successfully installed.

Any thoughts?

Python3 version: Python 3.8.5
PHP version: 7.4.3
Platform: Ubuntu 20.04.1

**Comment by MrBrax** [comment]
What's the output of `whereis youtube-dl` `whereis streamlink` etc etc?

**Comment by MrBrax** [comment]
Also, are you running the webserver as the same user that installed the pip packages?

**Comment by bondurantdt** [comment]
Thanks for the reply, based on your info I installed the modules to the www-data user and pointed it to /var/www/.local/bin

**Comment by MrBrax** [comment]
It's a little bit weird of an installation for an user without a home dir, would probably work better with a global installation, but if it works that's great.
