### ISSUE TITLE
OAuth token doesn't get renewed?

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/TwitchAutomator#41]
I've been using last version without any problems (around one month at least), but yesterday I found out that the OAuth token wasn't valid anymore despite not changing anything related to TwitchAutomator/Twitch:

> 2021-03-29 05:00:00.793 | helper | <INFO> Calling subscribe for MOONMOON
2021-03-29 05:00:01.228 | helper | <FATAL> Sub return, sleep: Client error: `POST https://api.twitch.tv/helix/webhooks/hub` resulted in a `401 Unauthorized` response:
{"error":"Unauthorized","status":401,"message":"Invalid OAuth token"}

Since OAuth is fetched by TwitchAutomator, I would assume something is missing here, maybe TwitchAutomator does not renew the token when it expires?

----------

I resolved this by deleting the oauth.bin file and calling the sub API to subscribe again to the twitch streamers, but this should be automated (if it's not already and its just a bug)

**Comment by MrBrax** [comment]
it's supposed to renew automatically, and it does for me. are the mtime features of your filesystem broken, or a permissions issue maybe?

**Comment by KurtzPT** [comment]
I'm using docker. Permissions are fine, it can create/delete files from cache folder. I'm not sure about mtime features, doing a quick stat oauth.bin it gets the following:

![image](https://user-images.githubusercontent.com/14930057/113067791-ee1dc000-91b4-11eb-87dc-5f441bfac116.png)

**Comment by KurtzPT** [comment]
I noticed in the code that it should renew after 30 days, but what if the oauth expires before 30 days? (I'm not sure if it was my case since I already deleted the old oauth file)

**Comment by MrBrax** [comment]
it should expire after around 60 days, if the token is only fetched with this application i don't really see how it could expire

you can't really do a retry of the function if it fails, at least in the current form of the code, and invalid oauth token could mean many things

it would require a pretty big rewrite i think

**Comment by KurtzPT** [comment]
If that is the case I'm not sure what happened, I didn't change anything nor I use the token anywhere else. I guess I can wait and see what happens again after another 30days, maybe the token refreshes this time around.
