### ISSUE TITLE
Korean usernames

### ISSUE THREAD

**Issue by condor125** [MrBrax/TwitchAutomator#43]
Streams of users with Korean usernames won't get recorded, just getting a *.m3u8 and *.json.broken file.

**Comment by MrBrax** [comment]
Is there anything in the logs/software directory with verbose app output enabled?

**Comment by condor125** [comment]
streamlink_아잉츄___2021-04-21T12_28_23Z_42386318110_stdout.0.log

$ /usr/local/bin/streamlink --hls-live-restart --hls-live-edge 99999 --hls-timeout 200 --hls-segment-timeout 200 --hls-segment-threads 5 --twitch-disable-hosting --twitch-disable-ads --retry-streams 10 --retry-max 5 --twitch-disable-reruns --loglevel debug -o /var/TwitchAutomator/src/../public/vods/아잉츄__/아잉츄___2021-04-21T12_28_23Z_42386318110.ts --url twitch.tv/아잉츄__ --default-stream best
[cli][debug] OS:         Linux-4.19.0-14-amd64-x86_64-with-debian-10.9
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 2.1.1
[cli][debug] Requests(2.21.0), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=twitch.tv/아잉츄__
[cli][debug]  --loglevel=debug
[cli][debug]  --output=/var/TwitchAutomator/src/../public/vods/아잉츄__/아잉츄___2021-04-21T12_28_23Z_42386318110.ts
[cli][debug]  --url=twitch.tv/아잉츄__
[cli][debug]  --default-stream=['best']
[cli][debug]  --retry-streams=10.0
[cli][debug]  --retry-max=5
[cli][debug]  --hls-live-edge=99999
[cli][debug]  --hls-segment-threads=5
[cli][debug]  --hls-segment-timeout=200.0
[cli][debug]  --hls-timeout=200.0
[cli][debug]  --hls-live-restart=True
[cli][debug]  --twitch-disable-hosting=True
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-disable-reruns=True
[cli][info] Found matching plugin twitch for URL twitch.tv/아잉츄__
[plugins.twitch][debug] Getting live HLS streams for 아잉츄__
[cli][info] Waiting for streams, retrying every 10.0 second(s)
[plugins.twitch][debug] Getting live HLS streams for 아잉츄__
[plugins.twitch][debug] Getting live HLS streams for 아잉츄__
[plugins.twitch][debug] Getting live HLS streams for 아잉츄__
[plugins.twitch][debug] Getting live HLS streams for 아잉츄__
[plugins.twitch][debug] Getting live HLS streams for 아잉츄__
error: No playable streams found on this URL: twitch.tv/아잉츄__


Seems like a wrong url gets handed over to streamlink? The url should be twitch.tv/aingchuu

**Comment by MrBrax** [comment]
that disconnect from login name and display name is not something i've seen before, gotta test that

**Comment by MrBrax** [comment]
It's been too long since i worked on this, i'll see if i can re-learn the codebase some day.

**Comment by MrBrax** [comment]
so an update on this, the next major (breaking) release will most likely fix this, i just need to test it more

**Comment by condor125** [comment]
streamlink_maruemon1019_2021-08-09T09_59_20Z_43197316141_stderr.0.log

$ /usr/local/bin/streamlink --hls-live-restart --hls-live-edge 99999 --hls-timeout 200 --hls-segment-timeout 200 --hls-segment-threads 5 --twitch-disable-hosting --twitch-disable-ads --retry-streams 10 --retry-max 5 --twitch-disable-reruns -o /var/www/TwitchAutomator/src/../public/vods/maruemon1019/maruemon1019_2021-08-09T09_59_20Z_43197316141.ts **--url twitch.tv/마루에몽** --default-stream best

**Comment by MrBrax** [comment]
pushed a fix, seems like i forgot one place
