### ISSUE TITLE
eventsub-beta.wss.twitch.tv no longer up

### ISSUE THREAD

**Issue by matthudsonatx** [MrBrax/TwitchAutomator#445]
<ERROR> Error on event websocket: Error: getaddrinfo ENOTFOUND eventsub-beta.wss.twitch.tv

I'm guessing Twitch decided to make take the service out of beta; eventsub.wss.twitch.tv is valid. Hopefully I'm not the only one seeing this.

**Comment by MrBrax** [comment]
yes it's fixed on dev, just not pushed to main branch
