### ISSUE TITLE
Streams stuck in recording even hours after the stream

### ISSUE THREAD

**Issue by styler2go** [MrBrax/TwitchAutomator#5]
Is there any common issue for my issue?

Streams are still marked and seem to be recording but the stream ended hours ago.

I also get the message
> Not running, did it crash?

Which infos do you need to help me on that issue?

**Comment by styler2go** [comment]
Simply loading the page returns a ton of PHP notices:

![image](https://user-images.githubusercontent.com/2152144/97119354-f0648580-170f-11eb-9de7-567c93470f13.png)

**Comment by MrBrax** [comment]
What's in the built in logs? Is this in docker?

**Comment by styler2go** [comment]
No, this is not on a docker. Just a simple Linux-Machine

**Comment by MrBrax** [comment]
What about the logs? Should be in a collapsed section on the dashboard, or in the logs directory.

**Comment by styler2go** [comment]
Is it possible to contact you somewhere because the log file contains sensible data (the channel names) for me?

**Comment by MrBrax** [comment]
I have a Discord account, that seems hip these days. braxen#3871
