### ISSUE TITLE
Bind mount failed

### ISSUE THREAD

**Issue by CappiSteijns** [MrBrax/TwitchAutomator#53]
Hi, first of all, I am really new at this because i recently got an Synology NAS. 
So this is the first time I am working with SSH and docker-compose.yml. 

I placed all your files in : /volume1/homes (including docker-compose-pull and requirements.txt)

command: ''docker-compose pull'' works perfectly and finish 100%.
command: "docker-compose up -d" gives the following error:

------------------------------------------------------------------
root@CappiSteijns:/volume1/homes# docker-compose up -d
Starting saa ... error

- ERROR: for saa  Cannot start service saa: Bind mount failed: '/path/to/download/location' does not exists

- ERROR: for saa  Cannot start service saa: Bind mount failed: '/path/to/download/location' does not exists

- ERROR: Encountered errors while bringing up the project.
------------------------------------------------------------------

I'm really hoping someone can help me out, i've spent many hours trying to get it up and running and i've encountered many errors that I was able to solve after many hours and googling but at this point I am just really stuck. 

Thank you so much in advance!

**Comment by MrBrax** [comment]
not sure where you got `/path/to/download/location` from, but that should probably be a path on your local disk

**Comment by CappiSteijns** [comment]
> 
> 
> not sure where you got `/path/to/download/location` from, but that should probably be a path on your local disk

Yeah, i geuss thats kind of the issue, i looked at a lot of files but I dont know here to change the folder structure or what to do next?

**Comment by MrBrax** [comment]
that must be something you edited in, check your config files

**Comment by CappiSteijns** [comment]
> 
> 
> that must be something you edited in, check your config files
> 
> also, no idea what `saa` is, sounds like you're trying to set up a completely different program

There was indeed another file in there...
I followed the steps from starkayc from the issue:Docker Install via Portainer, and finally got it started up!!

But now when I want to download an VOD i get the following error:
![afbeelding](https://user-images.githubusercontent.com/84481241/119743177-92f10c80-be89-11eb-9c3f-6f383fe3fe52.png)
What can i do?

Also, do i need to configure some stuff in the ''config''? I didnt change anything and dont know if i should change something for example: Instance ID, Twitch client ID , Twitch secret etc. Do i need to fill that in?

**Comment by MrBrax** [comment]
yes, for basic functionality you should at least enter the twitch stuff

**Comment by CappiSteijns** [comment]
> 
> 
> yes, for basic functionality you should at least enter the twitch stuff

Got it working except it doesn't want to sub. When i run the cron/sub job I get the following:
![afbeelding](https://user-images.githubusercontent.com/84481241/120087422-0d1ecc80-c0e8-11eb-8fe0-e2ee8ed7cb40.png)
![afbeelding](https://user-images.githubusercontent.com/84481241/120087438-393a4d80-c0e8-11eb-8de2-ef0b5aa00021.png)

What can I do to fix this?

**Comment by MrBrax** [comment]
app url needs to be set to an address where your webserver is publically accessible from the internet
