### ISSUE TITLE
Interface password no longer working

### ISSUE THREAD

**Issue by condor125** [MrBrax/TwitchAutomator#54]
The password protection for the web interface is no longer working. Browser behaves like I entered a wrong username/password.

**Comment by MrBrax** [comment]
are you sure you're actually inputting the correct information? nothing has changed with the authentication system. tried another browser?

**Comment by condor125** [comment]
Turs out it stopped working because I recently switched to Cloudflare DNS and Cloudflare apparently breaks HTTP basic auth. Switched back to previous DNS provider and login works again.
