### ISSUE TITLE
Deprecation of WebSub-based Webhooks

### ISSUE THREAD

**Issue by condor125** [MrBrax/TwitchAutomator#61]
subscribing to channels no longer works, log:

```
| helper | <FATAL> Sub return, sleep: Client error: `POST https://api.twitch.tv/helix/webhooks/hub` resulted in a `404 Not Found` response:
{"error":"Not Found","status":404,"message":"WebSub is deprecated and will be shutdown on September 16, 2021. Applicatio (truncated...)
```

https://discuss.dev.twitch.tv/t/deprecation-of-websub-based-webhooks/32152

**Comment by MrBrax** [comment]
well shit, guess i have a lot of work to do

**Comment by MrBrax** [comment]
> Call the POST https://api.twitch.tv/helix/eventsub/subscriptions endpoint with the subscription details in the request body. The URL provided in the callback field MUST use HTTPS and port 443.

i guess this project is dead to me now, unless i find some workaround to this

**Comment by MrBrax** [comment]
i've started looking into the new system, and it's an absolute disaster. missing a lot of crucial information, need to rewrite pretty much the entire data parsing, and use a cache database. i'll see if i can fix this, but it's not looking too bright

**Comment by MrBrax** [comment]
I've had it recording for a couple days now without seemingly any problems, if anyone wants to test from the [eventsub branch](https://github.com/MrBrax/TwitchAutomator/tree/eventsub) branch, feel free before i release it later

**Comment by condor125** [comment]
I would like to test the eventsub branch, however adding new streamers doesn't seem to work and I don't have my old config file anymore

**Comment by MrBrax** [comment]
post logs if it's completely breaking

streamers are now in a separate file, so old config won't work for that

**Comment by condor125** [comment]
Log when I try to add a channel:
> 2021-07-29 00:51:08.309 | helper | <DEBUG> Fetched access token from cache
> 2021-07-29 00:51:08.313 | automator | <DEBUG> >>> https://example.com/api/v0/hook <<< accessed.
> 2021-07-29 00:51:08.315 | hook | <ERROR> Hook called with invalid JSON.
> 2021-07-29 00:51:08.317 | config | <SUCCESS> Saved config from settings/save
> 2021-07-29 00:51:08.437 | helper | <DEBUG> Fetched access token from cache
> 2021-07-29 00:51:08.440 | automator | <DEBUG> >>> https://example.com/api/v0/settings/list <<< accessed.
> 2021-07-29 00:51:08.634 | helper | <DEBUG> Fetched access token from cache
> 2021-07-29 00:51:08.637 | automator | <DEBUG> >>> https://example.com/api/v0/games/list <<< accessed.
> 2021-07-29 00:51:52.774 | helper | <DEBUG> Fetched access token from cache
> 2021-07-29 00:51:52.779 | automator | <DEBUG> >>> https://example.com/api/v0/channels/add <<< accessed.
> 2021-07-29 00:52:15.890 | helper | <DEBUG> Fetched access token from cache
> 2021-07-29 00:52:15.897 | automator | <DEBUG> >>> https://example.com/api/v0/channels/list <<< accessed.
> 2021-07-29 00:52:15.899 | job | <DEBUG> Channels list empty when getting, load from config.
> 2021-07-29 00:52:15.899 | api | <WARNING> No channels in channel list

Also, when visiting /api/v0/subscriptions/sub I'm getting

> Slim Application Error
> The application could not run because of the following error:
> 
> Details
> Type: Error
> Code: 0
> Message: Call to undefined method App\TwitchConfig::getStreamers()
> File: /var/www/TwitchAutomator/src/Traits/ApiSubs.php
> Line: 22
> Trace
> #0 /var/www/TwitchAutomator/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): App\Controller\ApiController->subscriptions_sub()
> #1 /var/www/TwitchAutomator/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
> #2 /var/www/TwitchAutomator/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
> #3 /var/www/TwitchAutomator/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
> #4 /var/www/TwitchAutomator/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
> #5 /var/www/TwitchAutomator/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
> #6 /var/www/TwitchAutomator/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Routing\RouteRunner->handle()
> #7 /var/www/TwitchAutomator/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
> #8 /var/www/TwitchAutomator/vendor/slim/twig-view/src/TwigMiddleware.php(125): class@anonymous->handle()
> #9 /var/www/TwitchAutomator/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Views\TwigMiddleware->process()
> #10 /var/www/TwitchAutomator/vendor/tuupola/slim-basic-auth/src/HttpBasicAuthentication.php(187): class@anonymous->handle()
> #11 /var/www/TwitchAutomator/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Tuupola\Middleware\HttpBasicAuthentication->process()
> #12 /var/www/TwitchAutomator/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
> #13 /var/www/TwitchAutomator/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
> #14 /var/www/TwitchAutomator/public/index.php(151): class@anonymous->handle()
> #15 /var/www/TwitchAutomator/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Closure->{closure}()
> #16 /var/www/TwitchAutomator/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
> #17 /var/www/TwitchAutomator/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
> #18 /var/www/TwitchAutomator/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
> #19 /var/www/TwitchAutomator/public/index.php(166): Slim\App->run()
> #20 {main}

**Comment by MrBrax** [comment]
subscriptions don't seem to require renewal now, so i'm not sure if the subs endpoint is needed anymore.

from what i can see, you must have downloaded an older version, that function no longer exists at that place.

**Comment by MrBrax** [comment]
or i forgot to do a commit, oops

**Comment by condor125** [comment]
`/api/v0/subscriptions/sub` is working now.

I still can't add new channels, this is showing up in the log after I press the Add button:
> 2021-07-29 03:26:44.363 | helper | <DEBUG> Fetched access token from cache
> 2021-07-29 03:26:44.371 | automator | <DEBUG> >>> https://example.com/settings/newstreamer <<< accessed.

**Comment by MrBrax** [comment]
are you getting errors in your browser? doesn't sound like it's posting at all

**Comment by condor125** [comment]
`{"message":"No login provided.","status":"ERROR"}`

**Comment by MrBrax** [comment]
have you built the latest client? the word streamer has been replaced with channel and username -> login on those pages

**Comment by condor125** [comment]
Metadata doesn't get saved for some streams and aborting recording doesn't work. Otherwise everything works as expected 👍

**Comment by MrBrax** [comment]
metadata like the chapters and titles? seems to be working for me, any errors?

does it throw any errors while trying to kill jobs? i might have broken something there

**Comment by mr-flibble** [comment]
@MrBrax Will you please merge this branch before/after September 16? And maybe update docker containers?

**Comment by MrBrax** [comment]
pushed it to docker, not sure i remember how to do it properly
