### ISSUE TITLE
Error when adding second channel

### ISSUE THREAD

**Issue by mr-flibble** [MrBrax/TwitchAutomator#69]
Hello, I'm on new docker image 6.0.0 (thank you btw)
Chanel list is now in new file, so I want to re-add streams.

**Problem:**
I can add first channel no problem, but when adding second nothing happens.
If I enable debug logs, there is this error message under "Add" button:
` Add{ "message": "Slim Application Error", "exception": [ { "type": "TypeError", "code": 0, "message": "str_replace(): Argument #2 ($replace) must be of type array|string, float given", "file": "/var/www/twitchautomator/src/TwitchVOD.php", "line": 1283 } ] }
`
I cant also delete channel (with same error in docker logs)

If I add channel  manuály to /config/channels.json, then is visible in web channel list.
Is adding channels manually to JSON ok workaround?

Thanks
![image](https://user-images.githubusercontent.com/5197625/132982188-5ea4f68a-5f03-425d-86a3-c15674e17670.png)

**Comment by MrBrax** [comment]
whoops, not sure why that's suddenly a problem.. pushing new version to dockerhub

**Comment by mr-flibble** [comment]
Thanks! Just tested and it's fixed 👍  :))
