### ISSUE TITLE
Are subscriptions working?

### ISSUE THREAD

**Issue by null-dev** [MrBrax/TwitchAutomator#70]
First of all, thank you for writing this excellent program!

I noticed that the subscription cronjob handler is commented out: https://github.com/MrBrax/TwitchAutomator/blob/91b29b51fa99a0934fd77f528e4e7dae5003f9f1/src/Controller/CronController.php#L202 but the web UI still refers to it on the `/settings/cron` and `/about` pages

From my understanding, you've replaced it with a new endpoint: https://github.com/MrBrax/TwitchAutomator/blob/358ba40196115450423a70138d9e981b688003f5/src/Traits/ApiSubs.php#L19

So do I have to setup a cronjob that points to `/api/v0/subscriptions/sub`? Just want to make sure I'm doing everything correctly.

**Comment by MrBrax** [comment]
i don't really know how twitch does it right now, as far as i know, you only need to subscribe to an endpoint once (done when adding a new streamer) and then it just works forever

**Comment by null-dev** [comment]
Sweet, thanks for the clarification!

**Comment by n-st** [comment]
It looks like the subscription API used in TwitchAutomator at the moment has been deprecated and recently (2021-09-16) removed:
https://blog.twitch.tv/en/2021/06/16/deprecation-of-websub-based-webhooks/

The usual cronjob `curl https://twitchautomator.example.com/api/v0/cron/sub` returns to the HTTP client:

> <h1>Subbing...</h1><strong>Subbing to StreamerName...</strong><pre>Error: </pre><hr /><br>Checking subs status...<br>No sub data.<br>Saving subs data...

and logs to the webserver error log:

> Sub return, sleep: Client error: `POST https://api.twitch.tv/helix/webhooks/hub` resulted in a `404 Not Found` response:\n{"error":"Not Found","status":404,"message":"WebSub is deprecated and will be shutdown on September 16, 2021. Applicatio (truncated...)\n


According to `http://twitchautomator.example.com/api/v0/subscriptions/list`, no subscriptions are active, and TwitchAutomator doesn't seem to record any streams:

> {"message":"No subscriptions. Let cron do its job or visit the sub page.","status":"ERROR"}

---

Is this just a configuration error on my end, or is TwitchAutomator currently incompatible with Twitch?

(Note that according to Twitch, the old API may still be available to "grandfathered" API keys, so old TwitchAutomator installation might still work while mine does not.)

**Comment by MrBrax** [comment]
it is compatible with the new system, but there's still some old code left since i wasn't sure how twitch handles it now
