### ISSUE TITLE
Docker error with missing templates dir after recent merge

### ISSUE THREAD

**Issue by mr-flibble** [MrBrax/TwitchAutomator#74]
Hello, I just updated to[ latest docker ](https://hub.docker.com/r/mrbrax/twitchautomator/tags) and sadly TwitchAutomator is not starting anymore. On website is error 500 and in console this error: 

**Uncaught Twig\Error\LoaderError: The "/var/www/twitchautomator/public/../templates" directory does not exist ("/var/www/twitchautomator/public/../templates"). in /var/www/twitchautomator/vendor/twig/twig/src/Loader/FilesystemLoader.php:92**

Is this something on my end, or maybe problem in latest container?
Thanks :)

Full log:

> Attaching to twitchautomator_broker_1, twitchautomator_web_1, twitchautomator_cron_1
cron_1    | time="2021-12-03T14:32:49Z" level=info msg="read crontab: /etc/crontab"
broker_1  | yarn run v1.3.2
web_1     | 2021-12-03 14:32:49,743 INFO supervisord started with pid 1
broker_1  | $ node server.js
broker_1  | Starting on port 8765...
broker_1  | Websocket server now listening for connections.
web_1     | 2021-12-03 14:32:50,746 INFO spawned: 'nginx' with pid 7
web_1     | 2021-12-03 14:32:50,747 INFO spawned: 'php-fpm' with pid 8
web_1     | [03-Dec-2021 14:32:50] NOTICE: fpm is running, pid 8
web_1     | [03-Dec-2021 14:32:50] NOTICE: ready to handle connections
web_1     | 2021-12-03 14:32:51,771 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
web_1     | 2021-12-03 14:32:51,771 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
web_1     | 2021-12-03 14:32:54.486 | helper | <DEBUG> Fetched access token from cache
web_1     | NOTICE: PHP message: PHP Fatal error:  Uncaught Twig\Error\LoaderError: The "/var/www/twitchautomator/public/../templates" directory does not exist ("/var/www/twitchautomator/public/../templates"). in /var/www/twitchautomator/vendor/twig/twig/src/Loader/FilesystemLoader.php:92
web_1     | Stack trace:
web_1     | #0 /var/www/twitchautomator/vendor/slim/twig-view/src/Twig.php(93): Twig\Loader\FilesystemLoader->addPath()
web_1     | #1 /var/www/twitchautomator/public/index.php(34): Slim\Views\Twig::create()
web_1     | #2 {main}
web_1     |   thrown in /var/www/twitchautomator/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 92
web_1     | 2021/12/03 14:32:54 [error] 9#9: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Twig\Error\LoaderError: The "/var/www/twitchautomator/public/../templates" directory does not exist ("/var/www/twitchautomator/public/../templates"). in /var/www/twitchautomator/vendor/twig/twig/src/Loader/FilesystemLoader.php:92
web_1     | Stack trace:
web_1     | #0 /var/www/twitchautomator/vendor/slim/twig-view/src/Twig.php(93): Twig\Loader\FilesystemLoader->addPath()
web_1     | #1 /var/www/twitchautomator/public/index.php(34): Slim\Views\Twig::create()
web_1     | #2 {main}
web_1     |   thrown in /var/www/twitchautomator/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 92" while reading response header from upstream, client: 172.18.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:8082"
web_1     | 172.18.0.1 - - [03/Dec/2021:14:32:54 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" "94.112.61.84, " 0.029 0.028 . -

**Comment by MrBrax** [comment]
I see, seems like i forgot to remove the loading of templates

**Comment by MrBrax** [comment]
fix pushed, hopefully

**Comment by mr-flibble** [comment]
Thanks! Latest version solved problem and docker now runs : )
