### ISSUE TITLE
Abort recording icon does not work

### ISSUE THREAD

**Issue by condor125** [MrBrax/TwitchAutomator#81]
The Abort record icon does not work: "Invalid API endpoint"

**Comment by MrBrax** [comment]
Honestly, I'm not sure if this would be useful to bring back, it mostly caused errors, especially since it would freak out when streamer changed games and it tried to record again. I'll think about it.

**Comment by Prikith** [comment]
Maybe this would work better in combination with a feature to pause recording for a streamer where you don't have to delete them but it won't auto record

**Comment by MrBrax** [comment]
If that's your intended use case for the abort recording button then yeah that makes sense

**Comment by MrBrax** [comment]
added this in a recent push, untested but hopefully should work
