### ISSUE TITLE
unRAID + Docker + NginxProxyManager SSL issue

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/TwitchAutomator#86]
So after long time of using TwitchAutomator with synology, I'm now changing to unRaid.

I have a paid SSL certificate on my own domain and I'm using Nginx Proxy Manager to reverse proxy my hostname directly to the docker image ip/port. I can access dashboard on my browser using the domain, ssl is working according to the browser.

But once I set my `https://<subdomain>.<domain>` on app_url I get the following error:

` cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Any ideas on how to fix this?

**Comment by MrBrax** [comment]
Just curious, why paid? Letsencrypt has free certs.

Maybe the proxying chain breaks somehow with PHP, not sure.

**Comment by Serph91P** [comment]
> So after long time of using TwitchAutomator with synology, I'm now changing to unRaid.
> 
> I have a paid SSL certificate on my own domain and I'm using Nginx Proxy Manager to reverse proxy my hostname directly to the docker image ip/port. I can access dashboard on my browser using the domain, ssl is working according to the browser.
> 
> But once I set my `https://<subdomain>.<domain>` on app_url I get the following error:
> 
> ` cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`
> 
> Any ideas on how to fix this?

Hey also using unRAID here, working fine with SWAG maybe try this one. Nginx has a lot of problems for me on unRAID. Also how did you setup the docket, and how did you setup the the docket to issue the cert to twitchautomator?

**Comment by MrBrax** [comment]
i pushed a commit to develop that might fix it by using an up to date certificate store, maybe try that, needs manual building though

**Comment by KurtzPT** [comment]
> Just curious, why paid? Letsencrypt has free certs.

It was for ease of use (Letsencrypt doesn't have wildcard subdomain support, so I would have to create one cert per subdomain) and I also got a deal for it which sealed the deal for me. 

> Also, where does the error appear? In the settings error or the PHP/Webserver logs?

Since the webpage just says fatal error, I had to search the PHP/Webserver logs. This is the full error line:
`NOTICE: PHP message: PHP Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/twitchautomator/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:208`

> Hey also using unRAID here, working fine with SWAG maybe try this one. Nginx has a lot of problems for me on unRAID. Also how did you setup the docket, and how did you setup the the docket to issue the cert to twitchautomator?

I never had a problem with NginxProxyManager before, this is the first time a docker image doesn't play well with it. My setup currently is using docker-compose (https://forums.unraid.net/topic/114415-plugin-docker-compose-manager/) which I use the yml file provided in this repo for it. I didn't setup any certs on twitchautomator since the cert is just handled by nginxproxymanager (which is the only app exposed to the internet)


> i pushed a commit to develop that might fix it by using an up to date certificate store, maybe try that, needs manual building though

I'll try in a bit and see if it makes any difference.

**Comment by MrBrax** [comment]
Alright so something with Guzzle/PHP then. Hope the fix works then.

**Comment by KurtzPT** [comment]
> Alright so something with Guzzle/PHP then. Hope the fix works then.

I'm not sure if I did something wrong but using develop branch and docker-compose up build, I can't even open main page

Using local IP or domain, same error:
`2022/01/28 21:10:32 [error] 21#21: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.100.101, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.100.110:5600"`

I also saw an error popping up while building:
`Collecting lxml<5.0,>=4.6.4
  Downloading lxml-4.7.1.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gbdsual7/lxml_802b23f96c6647f88fca5e5286632d62/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gbdsual7/lxml_802b23f96c6647f88fca5e5286632d62/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0_telfw2
         cwd: /tmp/pip-install-gbdsual7/lxml_802b23f96c6647f88fca5e5286632d62/
    Complete output (3 lines):
    Building lxml version 4.7.1.
    Building without Cython.
    Error: Please make sure the libxml2 and libxslt development packages are installed.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/84/74/4a97db45381316cd6e7d4b1eb707d7f60d38cb2985b5dfd7251a340404da/lxml-4.7.1.tar.gz#sha256=a1613838aa6b89af4ba10a0f3a972836128801ed008078f8c1244e65958f1b24 (from https://pypi.org/simple/lxml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by MrBrax** [comment]
i did change the base nginx+php repo, that could have messed things up, gonna build myself and check

**Comment by MrBrax** [comment]
alright fixed the build issue

**Comment by KurtzPT** [comment]
> alright fixed the build issue

It fixed the python error, but for some reason I'm still having the issue where I cannot connect at all to the webpage.

**Comment by MrBrax** [comment]
alright figured it out, php updated to 8 and php-fpm socket got changed

**Comment by KurtzPT** [comment]
> alright figured it out, php updated to 8 and php-fpm socket got changed

That fixed it! Unfortunately the same SSL issue seems to still appear  (now directly on the webpage)

`External app url could not be contacted on 'https://<host>/api/v0/hook' due to a Guzzle error: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

**Comment by MrBrax** [comment]
Something must be weird with the SSL cert then, check it with this: https://www.ssllabs.com/ssltest/

**Comment by KurtzPT** [comment]
> Something must be weird with the SSL cert then, check it with this: https://www.ssllabs.com/ssltest/

Not sure what you want to check on the SSL cert with this test but I ran and everything is fine:

![image](https://user-images.githubusercontent.com/14930057/151661762-c7ae3afc-9365-4588-8281-d5c466baeb45.png)

Like I said previously I use a bunch of different docker images that are exposed to the internet via reverse proxy (nginxproxymanager) with SSL support turned on and I never had this issue.

**Comment by MrBrax** [comment]
Nothing wrong with the CA chain? Something is clearly wrong with the way that cURL validates the cert

**Comment by KurtzPT** [comment]
So it seems my cert didn't had the intermediate cert that connects to the root cert and this while this still works via browser (since it shows everything okay with it), curl does not really like it.

It also seems not one of my other docker images was using curl in this matter by querying the hostname so this made quite the confusion for me. I fixed it by adding the intermediate ssl cert on my nginxproxymanager config, now I can add the app_url without any error.

**Comment by MrBrax** [comment]
Yep, cert chains can be a hassle :)
