### ISSUE TITLE
Viewer count not appearing

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/TwitchAutomator#87]
So it seems the viewer count is not showing up on each offset segments:

![image](https://user-images.githubusercontent.com/14930057/151683453-23507881-08b9-477d-be09-115f1d308bcf.png)

It appears that icon instead. 

Not sure if this is a bug or just not implemented (tho the screen in the main repo shows the viewer count)

**Comment by MrBrax** [comment]
Pretty sure it got removed with the new eventsub update

**Comment by KurtzPT** [comment]
I'll try this new commit and report back.

**Comment by KurtzPT** [comment]
![image](https://user-images.githubusercontent.com/14930057/152070348-fd53c54e-639f-4045-8fd5-6b66b8db4773.png)

Working now!
