### ISSUE TITLE
PHP errors

### ISSUE THREAD

**Issue by condor125** [MrBrax/TwitchAutomator#9]
Hi,

I'm getting the following php errors when trying to run this:

```Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Notice: Undefined index: default in /var/TwitchAutomator-master/src/TwitchConfig.php on line 171

Warning: copy(/var/TwitchAutomator-master/src/../config/config.json): failed to open stream: No such file or directory in /var/TwitchAutomator-master/src/TwitchConfig.php on line 155

Warning: file_put_contents(/var/TwitchAutomator-master/src/../config/config.json): failed to open stream: No such file or directory in /var/TwitchAutomator-master/src/TwitchConfig.php on line 157

Warning: file_get_contents(/var/TwitchAutomator-master/src/../config/config.json): failed to open stream: No such file or directory in /var/TwitchAutomator-master/src/TwitchConfig.php on line 120

Fatal error: Uncaught TypeError: json_decode() expects parameter 1 to be string, bool given in /var/TwitchAutomator-master/src/TwitchConfig.php:120 Stack trace: #0 /var/TwitchAutomator-master/src/TwitchConfig.php(120): json_decode() #1 /var/TwitchAutomator-master/src/TwitchConfig.php(208): App\TwitchConfig::loadConfig() #2 /var/TwitchAutomator-master/vendor/composer/ClassLoader.php(444): include('/var/TwitchAuto...') #3 /var/TwitchAutomator-master/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile() #4 [internal function]: Composer\Autoload\ClassLoader->loadClass() #5 /var/TwitchAutomator-master/src/TwitchHelper.php(867): spl_autoload_call() #6 /var/TwitchAutomator-master/vendor/composer/ClassLoader.php(444): include('/var/TwitchAuto...') #7 /var/TwitchAutomator-master/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile() #8 [internal function]: Composer\Autoload\ClassLoader->loadClass() #9 /var/TwitchAutomator-master/public/index.php(30): spl_autoload_call() #10 {main} thrown in /var/TwitchAutomator-master/src/TwitchConfig.php on line 120
```

Any help would be appreciated, thanks.

**Comment by MrBrax** [comment]
a bit weird, it should be able to write the config, permissions issue?

**Comment by condor125** [comment]
I already changed the ownership and permissions of /var/TwitchAutomator-master/
```
sudo chown -R www-data:www-data /var/TwitchAutomator-master/
sudo chmod -R 755 /var/TwitchAutomator-master/
```
I also tried to set the permsissions to 777, same result.

**Comment by MrBrax** [comment]
did you update? i removed my config and it generated it again

**Comment by condor125** [comment]
I just installed everything from scratch, now I'm getting:

```
Warning: file_put_contents(/var/TwitchAutomator-master/src/../config/config.json): failed to open stream: No such file or directory in /var/TwitchAutomator-master/src/TwitchConfig.php on line 165

Fatal error: Uncaught Exception: Could not generate config, please check your permissions in /var/TwitchAutomator-master/src/TwitchConfig.php:122 Stack trace: #0 /var/TwitchAutomator-master/src/TwitchConfig.php(216): App\TwitchConfig::loadConfig() #1 /var/TwitchAutomator-master/vendor/composer/ClassLoader.php(444): include('/var/TwitchAuto...') #2 /var/TwitchAutomator-master/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile() #3 [internal function]: Composer\Autoload\ClassLoader->loadClass() #4 /var/TwitchAutomator-master/src/TwitchHelper.php(867): spl_autoload_call() #5 /var/TwitchAutomator-master/vendor/composer/ClassLoader.php(444): include('/var/TwitchAuto...') #6 /var/TwitchAutomator-master/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile() #7 [internal function]: Composer\Autoload\ClassLoader->loadClass() #8 /var/TwitchAutomator-master/public/index.php(29): spl_autoload_call() #9 {main} thrown in /var/TwitchAutomator-master/src/TwitchConfig.php on line 122
```

**Comment by MrBrax** [comment]
does the config directory actually exist?

**Comment by condor125** [comment]
no, config directory does not exist

**Comment by MrBrax** [comment]
yeah i must have gitted it out recently, it should create it now, and it's included with gitkeep

**Comment by condor125** [comment]
OK I created the config directory manually, now I'm getting

Hello, World! Visit /dashboard to continue.
Slim 4 doesn't seem to support relative redirects.

**Comment by MrBrax** [comment]
yes, it should work from then on

**Comment by condor125** [comment]
there is no dashboard directory

**Comment by MrBrax** [comment]
all url requests are handled via a router, your webserver should be pointing to the /public directory as the root, and depending on which one you use, it might need to redirect all queries to index.php

**Comment by MrBrax** [comment]
https://www.slimframework.com/docs/v4/start/web-servers.html

**Comment by condor125** [comment]
Got it working now, thank you.
But I ran into some new issues and questions:

Under /about it does not show Streamlink and youtube-dl I installed through pip. It does however show both when I install them through `apt install` and entering /usr/bin as python binary directory. But then they seem to be outdated (Streamlink 1.0.0 and youtube-dl 2019.01.17).

The dashboard says that I only have 1.61GB free space which is not true.

Does the script only record when a streamer goes live and not after they got added while they are live already?

When I click on force record, after a while I'm getting PHP error

> Fatal error: Uncaught Exception: Too many tries in /var/TwitchAutomator-master/src/TwitchAutomator.php:353 Stack trace: #0 /var/TwitchAutomator-master/src/TwitchAutomator.php(171): App\TwitchAutomator->download() #1 /var/TwitchAutomator-master/src/Routes/routes.php(89): App\TwitchAutomator->handle() #2 /var/TwitchAutomator-master/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Closure->{closure}() #3 /var/TwitchAutomator-master/vendor/slim/slim/Slim/Routing/Route.php(381): Slim\Handlers\Strategies\RequestResponse->__invoke() #4 /var/TwitchAutomator-master/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle() #5 /var/TwitchAutomator-master/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle() #6 /var/TwitchAutomator-master/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle() #7 /var/TwitchAutomator-master/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run() #8 /var/TwitchAutomator-master/vend in /var/TwitchAutomator-master/src/TwitchAutomator.php on line 353


and this shows up in the log:

> 2020-11-19 14:35:54.560 <INFO> Create VOD JSON: Bonjwa_2020-11-19T10_30_17Z_40045569884.json
> 2020-11-19 14:35:54.571 <WARNING> Saving JSON of Bonjwa_2020-11-19T10_30_17Z_40045569884 with no chapters!!
> 2020-11-19 14:35:54.582 <SUCCESS> Saving JSON of Bonjwa_2020-11-19T10_30_17Z_40045569884 (create json)
> 2020-11-19 14:35:54.593 <WARNING> JSON has been changed since loading of Bonjwa_2020-11-19T10_30_17Z_40045569884
> 2020-11-19 14:35:54.658 <WARNING> Saving JSON of Bonjwa_2020-11-19T10_30_17Z_40045569884 with no chapters!!
> 2020-11-19 14:35:54.666 <SUCCESS> Saving JSON of Bonjwa_2020-11-19T10_30_17Z_40045569884 (stream download)
> 2020-11-19 14:35:54.674 <INFO> Refreshing JSON on Bonjwa_2020-11-19T10_30_17Z_40045569884!
> 2020-11-19 14:35:54.681 <ERROR> No chapters on Bonjwa_2020-11-19T10_30_17Z_40045569884!
> 2020-11-19 14:35:54.692 <WARNING> Saving JSON of Bonjwa_2020-11-19T10_30_17Z_40045569884 with no chapters!!
> 2020-11-19 14:35:54.700 <SUCCESS> Saving JSON of Bonjwa_2020-11-19T10_30_17Z_40045569884 (is_capturing set)
> 2020-11-19 14:35:54.708 <INFO> Update game for Bonjwa_2020-11-19T10_30_17Z_40045569884
> 2020-11-19 14:35:54.715 <INFO> Refreshing JSON on Bonjwa_2020-11-19T10_30_17Z_40045569884!
> 2020-11-19 14:35:54.727 <ERROR> No chapters on Bonjwa_2020-11-19T10_30_17Z_40045569884!
> 2020-11-19 14:35:54.734 <SUCCESS> Saving JSON of Bonjwa_2020-11-19T10_30_17Z_40045569884 (game update)
> 2020-11-19 14:35:54.741 <SUCCESS> Game updated on Bonjwa to Minecraft (Mohin genau. Honor hier. Ab 16 Uhr They Are Billions !Lava)
> 2020-11-19 14:35:54.747 <INFO> Refreshing JSON on Bonjwa_2020-11-19T10_30_17Z_40045569884!
> 2020-11-19 14:35:54.759 <SUCCESS> Saving JSON of Bonjwa_2020-11-19T10_30_17Z_40045569884 (dt_capture_started set)
> 2020-11-19 14:35:54.766 <INFO> Starting capture with filename Bonjwa_2020-11-19T10_30_17Z_40045569884.ts
> 2020-11-19 14:36:52.485 <INFO> Finished capture with filename Bonjwa_2020-11-19T10_30_17Z_40045569884.ts
> 2020-11-19 14:36:52.496 <ERROR> 410 error for Bonjwa_2020-11-19T10_30_17Z_40045569884
> 2020-11-19 14:36:58.767 <ERROR> File Bonjwa_2020-11-19T10_30_17Z_40045569884.ts never got created.
> 2020-11-19 14:36:58.779 <WARNING> Panic handler for Bonjwa_2020-11-19T10_30_17Z_40045569884, no captured file!
> 2020-11-19 14:36:58.790 <WARNING> No such config variable 'download_retries'.
> 2020-11-19 14:36:58.801 <ERROR> Giving up on downloading, too many tries for Bonjwa_2020-11-19T10_30_17Z_40045569884

Could this be due to outdated Streamlink version?

**Comment by MrBrax** [comment]
Does pip install them into /usr/bin?

The /var/ partition might be just that small, depends on your setup.

It's very possible that it breaks with that old software, yes.

It only records when they go live, not when you add them.

Force record should work, as long as the utilities work.

**Comment by MrBrax** [comment]
The logs/software/ folder contains logs for the utilities, you can check those too, but I'd recommend trying to update streamlink and such first.

**Comment by condor125** [comment]
pip installs them to ~/.local/lib/python3.7/site-packages/
But when I enter that path they do not show up under /about

**Comment by MrBrax** [comment]
Those are probably the python source files. What happens if you run `whereis streamlink` or `whereis youtube-dl`

**Comment by condor125** [comment]
streamlink: /usr/bin/streamlink /usr/share/streamlink /home/pi/.local/bin/streamlink /usr/share/man/man1/streamlink.1.gz

youtube-dl: /usr/bin/youtube-dl /home/pi/.local/bin/youtube-dl /usr/share/man/man1/youtube-dl.1.gz

**Comment by MrBrax** [comment]
you should probably set it to `~/.local/bin/` then if you're running the webserver on the `pi` user

**Comment by condor125** [comment]
the webserver is run by the user `www-data`.
I installed the packages now through `sudo pip` instead of `pip`, entering `/usr/local/bin` as Python binary directory and now recording seems to work fine. Thank you for your efforts!
"Free space" in /dasboard still bothers me a bit though. I'm running Raspbian that only has two partitions and on the main partition there are about 60GB of free space.

**Comment by MrBrax** [comment]
It will fill up the ~2gb of space then. You'll need to expand the /var/ partition or place the app directory somewhere else where it has more space, and point your webserver to it. I guess you could mount a drive or something to the vods folder too

**Comment by condor125** [comment]
Maybe I'm overlooking something but /var/ does not seem to be on a separate partition

```
Disk /dev/mmcblk0: 59.5 GiB, 63864569856 bytes, 124735488 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x80bca99e

Device         Boot  Start       End   Sectors  Size Id Type
/dev/mmcblk0p1        8192    532479    524288  256M  c W95 FAT32 (LBA)
/dev/mmcblk0p2      532480 124735487 124203008 59.2G 83 Linux


pi@raspberrypi:~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        59G  2.5G   54G   5% /
devtmpfs        430M     0  430M   0% /dev
tmpfs           463M     0  463M   0% /dev/shm
tmpfs           463M  6.5M  456M   2% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           463M     0  463M   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   54M  199M  22% /boot
tmpfs            93M     0   93M   0% /run/user/1000
```

**Comment by MrBrax** [comment]
that's very strange then, maybe some limit for www-data?

**Comment by condor125** [comment]
I'm running this on a VPS now and free space is displayed correctly.
Automatic recording when a streamer goes live does not work for me, only force record works so far.
Visting `/sub` seems to work fine, but when visiting `/subs` I'm getting `array(3) { ["total"]=> int(0) ["data"]=> array(0) { } ["pagination"]=> array(0) { } }`
Chat dumping also does not work for me. When activated, I'm getting `<ERROR> TTY not supported` in the log.

**Comment by MrBrax** [comment]
It doesn't seem to sub properly then, is the app_url set properly, and can /hook be accessed?

TTY not supported is fine. That feature seems pretty broken anyway, php seems to mess with multithreading.

**Comment by condor125** [comment]
I'm using the calculated app URL from the settings page which is the same as my server's IP.
When visiting `/hook` I'm getting "No data supplied"

**Comment by MrBrax** [comment]
i just pushed a new update, apply it and run sub again, then check the app logs

**Comment by condor125** [comment]
```
<INFO> Calling subscribe for streamerName
<INFO> Sub response code: 202
<INFO> Sent subscribe request for streamerName (ID)
```

**Comment by MrBrax** [comment]
No `<INFO> Received hub challenge for userid ID` ? Seems like either the app_url is wrong or twitch somehow can't access your server

**Comment by MrBrax** [comment]
I added a sanity check for the app_url variable. You could try setting it again, but i'm not sure if that's the issue here.

**Comment by condor125** [comment]
OK seems it was my fault, I had added basic auth in /public via .htaccess
When I disable it, I'm getting the hub challenge in the log and automatic recording works.

**Comment by MrBrax** [comment]
alright! you can set basic auth via the password field in settings
