### ISSUE TITLE
TA Player - chat giving out errors on console.

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/TwitchAutomator#90]
Tried out to play a record with chat, comments are stuck at loading and using the devtools on chrome I see the following error:

![image](https://user-images.githubusercontent.com/14930057/152655315-35a2afcb-15f7-44d1-8267-b30e384fbd74.png)

**Comment by MrBrax** [comment]
seems like both files can't be found, are the network requests looking good?

**Comment by KurtzPT** [comment]
files are on the folder and the network requests seem fine:

![image](https://user-images.githubusercontent.com/14930057/152655539-d150e1b8-a4ad-4461-9b56-c374d7471812.png)

**Comment by MrBrax** [comment]
what about file contents? looks like it's just returning html

**Comment by KurtzPT** [comment]
> what about file contents? looks like it's just returning html

You mean the response tab on devtools? Or the contents of the file itself?

**Comment by MrBrax** [comment]
the response yeah, seems like it's returning a redirect or something

**Comment by KurtzPT** [comment]
Yes it seems its a html with the body:

> We're sorry but twitchautomator-client doesn't work properly without JavaScript enabled. Please enable it to continue.

Not sure why because I don't think I have javascript disabled.

**Comment by MrBrax** [comment]
it's the rewrite when it doesn't find a file on the server, then it serves the gui instead with wrong paths

there must be something wrong with the file url, check so that it matches up exactly with the one on disk, something must be wrong in the code somewhere

**Comment by KurtzPT** [comment]
Found the issue, URL is using the chat with the ext ".chatdump" but all my chat files have the ext ".chat"

After renaming my chat file to use .chatdump as an extension, it started working.

**Comment by MrBrax** [comment]
do you download the chat files from twitch or dump it while the stream is happening? they get different extensions depending on which one, no way to select in the player though

**Comment by KurtzPT** [comment]
Since TwitchDownloader on docker is not working (more on that on another issue I created), I think TA is using the python TCD after the stream stops, so I belive its getting it directly from the VOD on twitch.

**Comment by MrBrax** [comment]
under basic there's an option to live capture the chat with a script of mine in case the vod never gets saved, the regular option uses tcd yeah

**Comment by KurtzPT** [comment]
Also with this chat file, I still have the issue where it only shows messages without text and just with one emote.

**Comment by KurtzPT** [comment]
Might need to update docker to use the TwitchDownloader instead, since it seems more updated than the TCD?

**Comment by KurtzPT** [comment]
> under basic there's an option to live capture the chat with a script of mine in case the vod never gets saved, the regular option uses tcd yeah

I never used that live recording option, so it's TCD.

**Comment by MrBrax** [comment]
i don't think i ever used twitchdownloader to download the chat, it was for burning the chat into a video file

**Comment by MrBrax** [comment]
and unless tcd changed the format of chat dumps i don't really know why it would behave like that, could you post a snippet of the dump?

**Comment by KurtzPT** [comment]
> i don't think i ever used twitchdownloader to download the chat, it was for burning the chat into a video file

I never could use that option since docker never supported it unfortunately

> and unless tcd changed the format of chat dumps i don't really know why it would behave like that, could you post a snippet of the dump?

```
{
    "comments": [
        {
            "_id": "d45128f7-71e7-467b-a473-0dce23a5fb06",
            "channel_id": "121059319",
            "commenter": {
                "_id": "84692764",
                "bio": "lmao",
                "created_at": "2015-03-08T07:24:13.677475Z",
                "display_name": "spyther1",
                "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/8d6f418a-b224-46db-8eeb-dd3133b1f58e-profile_image-300x300.png",
                "name": "spyther1",
                "type": "user",
                "updated_at": "2022-01-25T23:15:55.123931Z"
            },
            "content_id": "1287172005",
            "content_offset_seconds": 0.168,
            "content_type": "video",
            "created_at": "2022-02-04T23:03:59.868Z",
            "message": {
                "body": "cactus_jack__ peepoD",
                "fragments": [
                    {
                        "text": "cactus_jack__ peepoD"
                    }
                ],
                "is_action": false,
                "user_badges": [
                    {
                        "_id": "subscriber",
                        "version": "12"
                    }
                ],
                "user_color": "#00FF7F",
                "user_notice_params": {}
            },
            "source": "chat",
            "state": "published",
            "updated_at": "2022-02-04T23:03:59.868Z"
        },{
            "_id": "8498f8d2-6af6-46ff-bb9d-9025b4f6ed6d",
            "channel_id": "121059319",
            "commenter": {
                "_id": "70788205",
                "bio": null,
                "created_at": "2014-09-08T00:03:41.37606Z",
                "display_name": "overkill_please",
                "logo": "https://static-cdn.jtvnw.net/user-default-pictures-uv/ce57700a-def9-11e9-842d-784f43822e80-profile_image-300x300.png",
                "name": "overkill_please",
                "type": "user",
                "updated_at": "2021-12-01T02:17:19.374981Z"
            },
            "content_id": "1287172005",
            "content_offset_seconds": 11452.497,
            "content_type": "video",
            "created_at": "2022-02-05T02:14:52.197Z",
            "message": {
                "body": "Prayge MONSTER HUNTER WORLD Prayge",
                "fragments": [
                    {
                        "text": "Prayge MONSTER HUNTER WORLD Prayge"
                    }
                ],
                "is_action": false,
                "user_badges": [
                    {
                        "_id": "premium",
                        "version": "1"
                    }
                ],
                "user_notice_params": {}
            },
            "source": "chat",
            "state": "published",
            "updated_at": "2022-02-05T02:14:52.197Z"
        }
```

**Comment by MrBrax** [comment]
for at least one of my channels it seems to be working now on dev

**Comment by KurtzPT** [comment]
Everything seems to be working now, including the chat is being correctly displayed now.

**Comment by MrBrax** [comment]
nice nice
