### ISSUE TITLE
Legacy Twitch API v5 Shutdown

### ISSUE THREAD

**Issue by TGCFabian** [MrBrax/TwitchAutomator#92]
Hey there!
I just got a email from Twitch notifying me that TwitchAutomator uses API V5 Calls

They plan to shut down the V5 api on February 28, 2022

As i rely on TwitchAutomator to record my vods, i'd love this to be updated
I Have no personal experience with the Twitch API

They stated it was related to the following query
``GET /kraken/videos/:vod_id/comments``

Thank you MrBrax for the awesome tool <3

**Comment by MrBrax** [comment]
Yes, chat dumping after the stream is over will no longer be possible, and there is no alternative (yet).

**Comment by MrBrax** [comment]
If the vod was deleted or never saved on twitch, that happens. A setting in the config makes TA record the chat while the stream is running, not using the API.

Nothing else should be affected.

**Comment by TGCFabian** [comment]
Ah yikes, good to know tho! Without Twitch Automator all my vods would have been lost lmfao
It sucks that i have to record a special audio track for just the twitch vod, 
TwitchAutomator was a saviour for me in that :D


To not clog this issue further (As its not such a majour issue thankfully)
Do you have other ways to contact you? Such as a discord? (Or whatever you think is handy)

**Comment by MrBrax** [comment]
Nice!

braxen#3871 on discord, but i never check my friend requests because there are just too many
