### ISSUE TITLE
Minor issue on about page

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/TwitchAutomator#96]
With TwitchDownloaderCLI path not defined I have the following on about page:

![image](https://user-images.githubusercontent.com/14930057/154856548-2d912e80-9cec-410a-862a-e703c71e2178.png)

Shouldn't it be "Not installed, not enabled" or something of the sort?

**Comment by KurtzPT** [comment]
Another issue on the about page:

```
NOTICE: PHP message: PHP Warning: Undefined array key "youtube-dl" in /var/www/twitchautomator/src/Controller/ApiController.php on line 414

NOTICE: PHP message: PHP Warning: Trying to access array offset on value of type null in /var/www/twitchautomator/src/Controller/ApiController.php on line 414
```

**Comment by MrBrax** [comment]
if you run it in docker it should install itself, but it's probably just broken because i haven't tested it

**Comment by KurtzPT** [comment]
I'm running in docker.

**Comment by MrBrax** [comment]
ok on my docker setup it shows the version now, should work
