### ISSUE TITLE
Twitch Vod Delete detection seems to not work properly?

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/TwitchAutomator#97]
As the title says, I have streams that are marked as VOD is missing on Twitch when in fact that's not true:

![image](https://user-images.githubusercontent.com/14930057/154856859-7e42d747-7e18-40af-b52c-e81e43bd0c9a.png)

Link: https://www.twitch.tv/videos/1293859054 

Running the endpoint `api/v0/cron/check_deleted_vods` seems to not change anything/unmark the delete vod from the stream.

**Comment by MrBrax** [comment]
is there any odd logging when you run the cron?

**Comment by KurtzPT** [comment]
The only thing I see after calling that endpoint:

```
2022-02-20 20:28:24.353 | cron | <INFO> Cronjob deleted check start
2022-02-20 20:28:24.378 | vodclass | <ERROR> No chapters on outerheaven_2022-02-10T22_07_51Z_45480164221!
2022-02-20 20:28:24.603 | vodclass | <ERROR> Trying to check vod valid while not finalized on sodapoppin_2022-02-20T19_19_21Z_45598808509
2022-02-20 20:28:24.604 | cron | <INFO> Cronjob deleted check end
```

**Comment by MrBrax** [comment]
oh right, there's a check in the cron thing that disables checking if it's removed. `?force=1` in the cron url to force it, not sure if i should disable the check considering vods rarely get un-deleted

**Comment by KurtzPT** [comment]
Ok it ran and it actually fixed it..

I think what happened is I again had the issue #41 (I think) and after that I think the vod checks failed and marked everything as VOD deleted.
