### ISSUE TITLE
TwitchAutomator is not recording an online Stream

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/TwitchAutomator#99]
Hello Again,

Sorry to write again so soon.

After the last issue, everything was running fine. But Yesterday it stopped suddenly recording. Have tested it now with my own stream. It wouldn't record anything. Looked at the logs no errors, nothing. So I decided to wipe the whole thing. I deleted everything from docker to folder to configs and subscriptions. And started completely fresh. Added only my own channel and went live. It's not recording or even showing any error, the only thing I see in the logs are me accessing the site. Today tried the same, went only for 15 min with my stream, noting. Also tried downloading some vods. Those are working, but with errors, I assume?

I will upload the entire log. Maybe you can make something out of it.
[log.txt](https://github.com/MrBrax/TwitchAutomator/files/8122928/log.txt)

**Comment by MrBrax** [comment]
there's no "subscription active" in your logs, events never reached your web server, check your config and domain name

**Comment by Serph91P** [comment]
> there's no "subscription active" in your logs, events never reached your web server, check your config and domain name

found it, closed
